import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {db} from "@/lib/db";
import {pageActor} from "@/lib/session";
import {homeForRole} from "@/lib/roles";
import {Shell,Heading} from "@/components/shell";
import {AcquirerChangeDecision} from "@/components/acquirer-change-forms";
type Proof={id:string;originalName:string;pages?:{id:string;originalName:string}[]};
type Snapshot={from:{id:string;name:string;email:string};to:{id:string;name:string;email:string};files:{id:string;acquirer:{reference:string;userId:string}}[];sourceProof:Proof;targetProof:Proof;transfer:{source:{reference:string}}|null};
export default async function Change({params}:{params:Promise<{id:string}>}){
 const actor=await pageActor();if(actor.role!=="ACQUIRER_AGENT")redirect(homeForRole(actor.role));const item=await db.acquirerChange.findUnique({where:{id:(await params).id}});if(!item)notFound();const data=item.snapshot as Snapshot;
 const users=await db.user.findMany({where:{id:{in:[item.preparedBy,item.reviewedBy??""]}},select:{id:true,name:true,personId:true}}),preparer=users.find(u=>u.id===item.preparedBy);
 return <Shell name={actor.name} staff><Link href="/gestion/changements" className="text-link">← Demandes</Link><Heading eyebrow="EXAMEN INDÉPENDANT" title={item.kind==="CONSOLIDATE"?"Regrouper les dossiers sous un compte":"Changer le titulaire de l’accès"}/><section className="panel"><p>Préparé par {preparer?.name??item.preparedBy} · {item.createdAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</p><p>{item.reason}</p><dl><dt>Compte d’origine</dt><dd>{data.from.name} · {data.from.email}</dd><dt>Compte conservé / nouveau titulaire</dt><dd>{data.to.name} · {data.to.email}</dd></dl>{item.kind==="CONSOLIDATE"?<p>Le compte d’origine sera désactivé. Les dossiers seront regroupés sous le compte conservé sans fusionner leurs pièces ni leurs conversations. Les sessions des deux comptes seront fermées.</p>:<p>L’accès à {data.transfer?.source.reference} sera retiré à l’ancien titulaire et accordé au nouveau. Les archives personnelles restent accessibles à leur propriétaire. Aucun titre foncier, signature ou paiement n’est créé.</p>}<h2>Dossiers examinés</h2>{data.files.map(f=><p key={f.id}><Link href={`/gestion/acquereurs/${f.id}`}>{f.acquirer.reference}</Link> · {f.acquirer.userId===data.from.id?"Compte d’origine":"Compte conservé"}</p>)}<h2>Preuves à examiner</h2>{([data.sourceProof,data.targetProof]).map((proof,index)=><div key={index}><h3>{index===0?"Origine":"Destination"}</h3>{(proof.pages??[proof]).map(p=><p key={p.id}><a href={`/api/documents/${p.id}`}>{p.originalName}</a></p>)}</div>)}{item.status==="PENDING"?<AcquirerChangeDecision id={item.id} author={actor.id===item.preparedBy} independent={actor.personId!==item.preparedPersonId&&actor.personId!==preparer?.personId}/>:<><h2>{item.status==="APPROVED"?"Demande approuvée":item.status==="REJECTED"?"Demande refusée":"Demande retirée"}</h2><p>{item.reviewReason}</p><p>{users.find(u=>u.id===item.reviewedBy)?.name} · {item.reviewedAt?.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</p></>}</section></Shell>;
}
