import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {pageActor} from "@/lib/session";
import {homeForRole} from "@/lib/roles";
import {db} from "@/lib/db";
import {Shell,Heading} from "@/components/shell";
import {ImportConfirmForm} from "@/components/registry-import-forms";
import {importHeaders,importStates,type ImportKind,type ImportRow} from "@/lib/registry-import-model";
export default async function Import({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{page?:string}>}){
 const actor=await pageActor();if(actor.role!=="ACQUIRER_AGENT")redirect(homeForRole(actor.role));const batch=await db.registryImport.findFirst({where:{id:(await params).id,actorId:actor.id}});if(!batch)notFound();
 const rows=batch.report as ImportRow[],errors=rows.filter(r=>r.state==="ERROR").length,created=rows.filter(r=>r.state==="CREATE").length,unchanged=rows.filter(r=>r.state==="EXISTS").length,warnings=rows.some(r=>r.warnings.length),completed=batch.status==="COMPLETED",expired=batch.expiresAt<=new Date();
 const page=Math.max(1,Math.min(Math.ceil(rows.length/50),Math.floor(Number((await searchParams).page))||1));
 return <Shell name={actor.name} staff><Link href="/gestion/imports" className="text-link">← Mes imports</Link><Heading title={batch.filename} eyebrow={batch.kind==="ACQUIRERS"?"IMPORT ACQUÉREURS":"IMPORT PARCELLES"}/>{completed?<p className="feedback success" role="status">Import terminé : {created} fiche(s) créée(s), {unchanged} déjà présente(s). Aucun compte ni rattachement n’a été créé par cet import.</p>:<p>{created} à créer · {unchanged} déjà présentes · {errors} à corriger</p>}<section className="panel"><h2>{completed?"Rapport de l’import":"Aperçu à vérifier"}</h2><div style={{overflowX:"auto"}}><table><thead><tr><th>Ligne</th>{importHeaders[batch.kind as ImportKind].map(h=><th key={h}>{h}</th>)}<th>Résultat</th></tr></thead><tbody>{rows.slice((page-1)*50,page*50).map(row=><tr key={row.line}><td>{row.line}</td>{[0,1,2].map(i=><td key={i} style={{overflowWrap:"anywhere",maxWidth:320}}>{row.values[i]||"—"}</td>)}<td><strong>{completed&&row.state==="CREATE"?"Créée":importStates[row.state]}</strong><p>{row.message}</p>{row.warnings.map(w=><p className="notice" key={w}>{w}</p>)}</td></tr>)}</tbody></table></div><div className="actions">{page>1&&<Link href={`?page=${page-1}`}>Précédent</Link>}{page*50<rows.length&&<Link href={`?page=${page+1}`}>Suivant</Link>}</div></section>{!completed&&<section className="panel"><h2>Validation</h2>{expired?<p>L’aperçu a expiré. Analysez de nouveau le fichier.</p>:errors?<p>Corrigez les lignes signalées puis analysez à nouveau le fichier. Aucun ajout n’a été effectué.</p>:<><p className="muted small">Cet aperçu est valable une heure. Toutes les lignes seront revérifiées à la confirmation.</p><ImportConfirmForm id={batch.id} created={created} warnings={warnings}/></>}<Link className="text-link" href="/gestion/imports">Analyser un nouveau fichier →</Link></section>}{completed&&<Link className="button" href={batch.kind==="ACQUIRERS"?"/gestion/acquereurs":"/gestion/parcelles"}>Ouvrir le registre</Link>}</Shell>;
}
