import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,rmSync,readdirSync,writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
test("Publications MyKipCity : relecture et audiences privées",async t=>{
 const root=mkdtempSync(join(tmpdir(),"kip-publications-"));process.env.DATABASE_URL=`file:${root}/db`;process.env.DEMO_MODE="true";process.env.DOCUMENTS_DIR=`${root}/documents`;
 execFileSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{env:process.env,stdio:"pipe"});
 const {db}=await import("../src/lib/db");const svc=await import("../src/lib/publications");
 try{
  for(const [id,role,personId] of [["author","ACQUIRER_AGENT","author"],["alias","ACQUIRER_AGENT","author"],["reviewer","ACQUIRER_AGENT","reviewer"],["buyer","ACQUIRER","buyer"],["other","ACQUIRER","other"],["pending","ACQUIRER","pending"],["admin","ADMIN","admin"],["finance","FINANCE_OFFICER","finance"]])await db.user.create({data:{id,role,personId,name:id,email:`${id}@test.invalid`}});
  for(const reference of ["P1","P2","P3"])await db.parcel.create({data:{id:reference,reference,area:400,cadastralReference:reference}});
  for(const id of ["buyer","other","pending"])await db.acquirer.create({data:{id,reference:`ACQ-${id.toUpperCase()}`,registeredName:id,email:`${id}@test.invalid`,personId:id,userId:id,file:{create:{declarations:{create:{reference:id==="other"?"P2":"P1",parcelId:id==="other"?"P2":"P1",contractNumber:"TEST",status:id==="pending"?"PENDING":"APPROVED"}}}}}});
  const buyerFile=await db.acquirerFile.findUniqueOrThrow({where:{acquirerId:"buyer"}});
  await db.parcelDeclaration.create({data:{fileId:buyerFile.id,reference:"P3",parcelId:"P3",status:"PENDING",contractNumber:"TEST"}});
  const content={title:"Information de démonstration",body:"Une information réservée aux membres autorisés.",audience:"MEMBERS",targetReference:""};
  const create=(c=content)=>svc.changePublication("author",{action:"save",version:0,content:c});
  const action=(id:string,kind:string,version:number,user="author")=>svc.changePublication(user,{action:kind,id,version,reason:"Recette de démonstration"});
  const publish=async(c=content)=>{const {id}=await create(c);await action(id,"submit",1);await action(id,"publish",2,"reviewer");return id;};
  let general="",personal="",parcel="";
  await t.test("Rôles, destinataires et brouillons",async()=>{
   await assert.rejects(svc.changePublication("buyer",{action:"save",version:0,content}),/réservé/);
   await assert.rejects(svc.changePublication("admin",{action:"save",version:0,content}),/réservé/);
   await assert.rejects(create({...content,audience:"PARCEL",targetReference:"MISSING"}),/inconnue/);
   await assert.rejects(create({...content,audience:"MEMBERS",targetReference:"P1"}));
   const {id}=await create();general=id;
   assert.equal((await svc.memberPublications("buyer")).count,0);
   await assert.rejects(svc.memberPublication("buyer",id),/inaccessible/);
   await assert.rejects(svc.staffPublication("finance",id),/réservée/);
   await assert.rejects(action(id,"publish",1,"reviewer"),/disponible/);
   await assert.rejects(svc.changePublication("reviewer",{action:"save",id,version:1,content}),/auteur/);
  });
  await t.test("Relecture distincte, verrouillage, concurrence et retour",async()=>{
   await action(general,"submit",1);
   await assert.rejects(action(general,"publish",2),/autre personne/);
   await assert.rejects(action(general,"publish",2,"alias"),/autre personne/);
   await assert.rejects(svc.changePublication("author",{action:"save",id:general,version:2,content}),/brouillon/);
   await action(general,"return",2,"reviewer");await action(general,"submit",3);
   const outcomes=await Promise.allSettled([action(general,"publish",4,"reviewer"),action(general,"publish",4,"reviewer")]);assert.equal(outcomes.filter(x=>x.status==="fulfilled").length,1);
   await assert.rejects(action(general,"withdraw",4),/changé/);
   personal=await publish({...content,title:"Uniquement pour buyer",audience:"ACQUIRER",targetReference:"ACQ-BUYER"});
   parcel=await publish({...content,title:"Uniquement parcelle P1",audience:"PARCEL",targetReference:"P1"});
   await publish({...content,title:"Parcelle P2 privée",audience:"PARCEL",targetReference:"P2"});
   await publish({...content,title:"Parcelle P3 en attente",audience:"PARCEL",targetReference:"P3"});
  });
  await t.test("Liste et URL directe respectent les rattachements actuels",async()=>{
   const visible=await svc.memberPublications("buyer");assert.deepEqual(new Set(visible.items.map(p=>p.id)),new Set([general,personal,parcel]));
   assert.deepEqual(new Set((await svc.memberPublications("buyer","P1")).items.map(p=>p.id)),new Set([general,personal,parcel]));
   await assert.rejects(svc.memberPublications("buyer","P2"),/inaccessible/);
   await assert.rejects(svc.memberPublications("buyer","P3"),/inaccessible/);
   await assert.rejects(svc.memberPublication("other",personal),/inaccessible/);
   await assert.rejects(svc.memberPublication("other",parcel),/inaccessible/);
   assert.equal((await svc.memberPublications("pending")).count,0);
   await assert.rejects(svc.memberPublication("pending",general),/inaccessible/);
   const dto=await svc.memberPublication("buyer",personal);assert.ok(!("authorPersonId" in dto));assert.ok(!("targetId" in dto));
   await db.parcelDeclaration.updateMany({where:{fileId:buyerFile.id,reference:"P1"},data:{status:"REJECTED"}});
   assert.equal((await svc.memberPublications("buyer")).count,0);await assert.rejects(svc.memberPublication("buyer",parcel),/inaccessible/);
   await db.parcelDeclaration.updateMany({where:{fileId:buyerFile.id,reference:"P1"},data:{status:"APPROVED"}});
   await db.user.update({where:{id:"buyer"},data:{active:false}});await assert.rejects(svc.memberPublication("buyer",general),/suspendu/);await db.user.update({where:{id:"buyer"},data:{active:true}});
  });
  await t.test("Le filtre terrain conserve les nouvelles générales, même après de nombreuses informations ciblées",async()=>{
   await db.parcelDeclaration.updateMany({where:{fileId:buyerFile.id,reference:"P3"},data:{status:"APPROVED"}});
   for(let i=0;i<13;i++)await publish({...content,title:`Information parcelle ${i}`,audience:"PARCEL",targetReference:"P1"});
   const dashboard=await svc.memberDashboardPublications("buyer","P1");
   assert.equal(dashboard.general.length,1);assert.equal(dashboard.general[0].id,general);assert.equal(dashboard.personal.length,3);
   assert.ok(!dashboard.personal.some(p=>p.targetReference==="P3"));
   const filtered=await svc.memberPublications("buyer","P3");
   assert.ok(filtered.items.some(p=>p.id===general));assert.ok(filtered.items.some(p=>p.id===personal));assert.ok(!filtered.items.some(p=>p.targetReference==="P1"));
   assert.equal((await svc.memberDashboardPublications("pending")).general.length,0);
  });
  await t.test("Retrait immédiat, corrections et nouvelle validation obligatoires",async()=>{
   await action(general,"withdraw",5,"reviewer");await assert.rejects(svc.memberPublication("buyer",general),/inaccessible/);
   await action(general,"reopen",6);
   await svc.changePublication("author",{action:"save",id:general,version:7,content:{...content,body:"Nouvelle version qui reste privée tant qu’elle n’est pas approuvée."}});
   await assert.rejects(svc.memberPublication("buyer",general),/inaccessible/);
   await action(general,"submit",8);await action(general,"publish",9,"reviewer");
   assert.match((await svc.memberPublication("buyer",general)).body,/Nouvelle version/);
   const events=await db.auditEvent.findMany({where:{objectId:general}});assert.equal(events.length,10);assert.ok(events.some(e=>e.action==="PUBLICATION_WITHDRAW"));
   await db.user.update({where:{id:"reviewer"},data:{active:false}});await assert.rejects(action(general,"withdraw",10,"reviewer"),/réservé/);
  });
  await t.test("Photos et rapports privés suivent la relecture, le destinataire et le retrait",async()=>{
   await db.user.update({where:{id:"reviewer"},data:{active:true}});
   const a=await import("../src/lib/publication-attachments");
   const item=await create({...content,audience:"PARCEL",targetReference:"P1"});
   const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=","base64");
   const pdf=Buffer.from("%PDF-1.4\nRapport fictif\n%%EOF");
   const input={publicationId:item.id,version:1,caption:"Photo de démonstration",takenOn:""};
   await assert.rejects(a.uploadPublicationAttachment("reviewer",input,"photo.png",png),/auteur/);
   await assert.rejects(a.uploadPublicationAttachment("buyer",input,"photo.png",png),/réservée/);
   await assert.rejects(a.uploadPublicationAttachment("author",{...input,takenOn:"9999-01-01"},"photo.png",png),/future/);
   await assert.rejects(a.uploadPublicationAttachment("author",{...input,takenOn:"2026-01-01"},"rapport.pdf",pdf),/uniquement/);
   await assert.rejects(a.uploadPublicationAttachment("author",input,"faux.png",Buffer.from("<svg/>")),/Format/);
   const photo=await a.uploadPublicationAttachment("author",input,"photo.png",png);
   await assert.rejects(a.readPublicationAttachment("buyer",photo.id),/inaccessible/);
   const uploads=await Promise.allSettled([1,2].map(()=>a.uploadPublicationAttachment("author",{...input,version:2,caption:"Rapport fictif"},"rapport.pdf",pdf)));
   assert.equal(uploads.filter(r=>r.status==="fulfilled").length,1);
   assert.equal(readdirSync(join(root,"documents/publications",item.id)).length,2);
   await action(item.id,"submit",3);
   await assert.rejects(a.uploadPublicationAttachment("author",{...input,version:4},"photo.png",png),/brouillon/);
   await action(item.id,"publish",4,"reviewer");
   assert.deepEqual((await a.readPublicationAttachment("buyer",photo.id)).bytes,png);
   assert.equal((await a.publicationAttachments("buyer",item.id)).length,2);
   for(const user of ["other","pending","admin","finance"])await assert.rejects(a.readPublicationAttachment(user,photo.id));
   const event=await db.auditEvent.findFirstOrThrow({where:{objectId:item.id,action:"PUBLICATION_PUBLISH"}});
   assert.equal(JSON.parse(event.detail).attachments.length,2);
   assert.ok(JSON.parse(event.detail).attachments.every((f:{sha256:string})=>f.sha256.length===64));
   const listing=await svc.memberDashboardPublications("buyer","P1");assert.ok(listing.personal.some(p=>p.attachments.some(f=>f.id===photo.id)));
   await action(item.id,"withdraw",5);
   await assert.rejects(a.readPublicationAttachment("buyer",photo.id),/inaccessible/);
   await action(item.id,"reopen",6);
   await a.removePublicationAttachment("author",{id:photo.id,version:7,reason:"Photo retirée de la publication"});
   await assert.rejects(a.readPublicationAttachment("author",photo.id),/inaccessible/);
   await assert.rejects(action(item.id,"submit",7),/changé/);
   await action(item.id,"submit",8);await action(item.id,"publish",9,"reviewer");
   const remaining=await a.publicationAttachments("buyer",item.id);assert.equal(remaining.length,1);assert.equal(remaining[0].mimeType,"application/pdf");
   const report=await db.publicationAttachment.findUniqueOrThrow({where:{id:remaining[0].id}});
   writeFileSync(join(root,"documents/publications",item.id,report.storageKey),"altéré");await assert.rejects(a.readPublicationAttachment("buyer",report.id),/intégrité/);
  });
  await t.test("Programmation, retrait avant diffusion et restauration imposent les mêmes droits",async()=>{
   const {id}=await create();const a=await import("../src/lib/publication-attachments");
   const photo=await a.uploadPublicationAttachment("author",{publicationId:id,version:1,caption:"Photo programmée",takenOn:""},"fictif.png",Buffer.from([137,80,78,71,13,10,26,10,0]));
   await action(id,"submit",2);
   await svc.changePublication("reviewer",{action:"publish",id,version:3,reason:"Contenu approuvé pour diffusion ultérieure.",publishAt:new Date(Date.now()+86400000).toISOString()});
   await assert.rejects(svc.memberPublication("buyer",id),/inaccessible/);await assert.rejects(a.readPublicationAttachment("buyer",photo.id),/inaccessible/);
   assert.ok(!(await svc.memberDashboardPublications("buyer")).general.some(p=>p.id===id));
   await action(id,"withdraw",4);await action(id,"archive",5);await assert.rejects(action(id,"restore",6,"reviewer"),/disponible/);
   await action(id,"restore",6);assert.equal((await svc.staffPublication("author",id)).status,"DRAFT");await assert.rejects(svc.memberPublication("buyer",id),/inaccessible/);
   await action(id,"submit",7);await action(id,"publish",8,"reviewer");assert.equal((await svc.memberPublication("buyer",id)).id,id);
  });
  await t.test("Comparaison libre : anciennes versions, destinataires et fichiers retirés",async()=>{
   const h=await import("../src/lib/publication-history");const a=await import("../src/lib/publication-attachments");
   const {id}=await create();const pdf=Buffer.from("%PDF-1.4\nHistorique privé\n%%EOF");
   const attachment=await a.uploadPublicationAttachment("author",{publicationId:id,version:1,caption:"Rapport initial",takenOn:""},"rapport.pdf",pdf);
   await a.removePublicationAttachment("author",{id:attachment.id,version:2,reason:"Rapport remplacé après correction"});
   for(let version=3;version<55;version++)await svc.changePublication("author",{action:"save",id,version,content:{...content,title:`Information révisée ${version}`,audience:"PARCEL",targetReference:"P1"}});
   const {versions}=await h.publicationHistory("reviewer",id);assert.equal(versions.length,55);assert.equal(versions[0].version,55);
   const diff=h.comparePublicationVersions(versions,"1","55")!;
   assert.equal(diff.left.content.title,content.title);assert.equal(diff.right.content.targetReference,"P1");
   assert.deepEqual(diff.changes,{title:true,body:false,audience:true,status:false,attachments:false});
   const files=h.comparePublicationVersions(versions,"2","3")!;assert.equal(files.left.attachments[0].id,attachment.id);assert.equal(files.right.attachments.length,0);assert.equal(files.changes.attachments,true);
   assert.equal(h.comparePublicationVersions(versions)!.left.version,54);
   assert.ok(Object.values(h.comparePublicationVersions(versions,"2","2")!.changes).every(v=>!v));
   for(const bad of ["0","56","2x","-1",""])assert.throws(()=>h.comparePublicationVersions(versions,bad,"55"),/introuvable/);
   await assert.rejects(a.readPublicationAttachment("author",attachment.id),/inaccessible/);
   assert.deepEqual((await a.readPublicationAttachment("reviewer",attachment.id,true)).bytes,pdf);
   for(const user of ["buyer","other","admin","finance"]){await assert.rejects(h.publicationHistory(user,id));await assert.rejects(a.readPublicationAttachment(user,attachment.id,true));}
   await db.user.update({where:{id:"reviewer"},data:{active:false}});
   await assert.rejects(h.publicationHistory("reviewer",id));await assert.rejects(a.readPublicationAttachment("reviewer",attachment.id,true));
   await db.user.update({where:{id:"reviewer"},data:{active:true}});
  });
 }finally{await db.$disconnect();rmSync(root,{recursive:true,force:true});}
});
