import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
test("Circuit Finance : séparation des personnes, gel et décisions",async t=>{
 const root=mkdtempSync(join(tmpdir(),"kip-review-"));process.env.DATABASE_URL=`file:${root}/db`;process.env.DOCUMENTS_DIR=`${root}/docs`;process.env.DEMO_MODE="true";
 execFileSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{env:process.env,stdio:"pipe"});
 const {db}=await import("../src/lib/db");const flow=await import("../src/lib/finance-review");const finance=await import("../src/lib/finance");const docs=await import("../src/lib/finance-documents");const {reassignFinance}=await import("../src/lib/assignments");
 const request={applicantName:"Recette",quality:"CANDIDATE",acquirerReference:"",phone:"",email:"",pathway:"HABITAT",need:"HABITAT",otherNeed:"",project:"Projet fictif",description:"",calendar:"",projectCost:"100",projectCurrency:"USD",contribution:"10",contributionCurrency:"USD",requested:"90",requestedCurrency:"USD",situation:"NONE",institution:"",contact:"",nextContact:"",initialDocuments:""};
 const budget={situationDate:"",dependents:0,lines:[{category:"REGULAR",amount:"100",currency:"USD",period:"MONTH",proof:"ESTIMATED",evidence:"",stability:""}],installmentSource:"",stressScenario:"",risks:"",analystNotes:""};
 const checks={identity:true,budget:true,documents:true};
 try{
  for(const [id,role,personId] of [["owner","FINANCE_OFFICER","p1"],["other","FINANCE_OFFICER","p2"],["reviewer","FINANCE_REVIEWER","p3"],["validator","FINANCE_VALIDATOR","p4"],["alias","FINANCE_REVIEWER","p1"],["unassigned","FINANCE_REVIEWER","p5"],["admin","ADMIN","p6"]])await db.user.create({data:{id,role,personId,name:id,email:`${id}@test.invalid`}});
  const item=await finance.createFinanceCase("owner",request);
  const submit=(version:number,reviewerId="reviewer",validatorId="validator")=>flow.submitReview("owner",{id:item.id,version,reviewerId,validatorId});
  await t.test("Soumission exige demande, budget et pièces contrôlées",async()=>{
   await assert.rejects(submit(1),/Complétez/);
   await finance.saveFinanceForm("owner",{id:item.id,version:1,code:"FIN-F02",data:budget});
   await assert.rejects(submit(2),/pièces attendues/);
  });
  const req=await docs.addRequirement("owner",{caseId:item.id,category:"IDENTITY",label:"Pièce fictive"});
  const doc=await docs.depositFinanceDocument("owner",{requirementId:req.id,version:0},"test.pdf",Buffer.from("%PDF-1.4 FICTIF"));
  await assert.rejects(submit(2),/pièces attendues/);
  await docs.reviewFinanceDocument("owner",{id:doc.id,decision:"ACCEPTED",reason:"Pièce examinée"});
  await t.test("Trois personnes distinctes et destinataires actifs",async()=>{
   await assert.rejects(submit(2,"alias"),/personnes distinctes/);
   await assert.rejects(submit(2,"owner"),/actifs/);
   await db.user.update({where:{id:"validator"},data:{active:false}});await assert.rejects(submit(2),/actifs/);await db.user.update({where:{id:"validator"},data:{active:true}});
   const results=await Promise.allSettled([submit(2),submit(2)]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);
   assert.equal((await finance.financeCase("owner",item.id)).status,"IN_REVIEW");
  });
  const initial=await db.financeReview.findUniqueOrThrow({where:{caseId_cycle:{caseId:item.id,cycle:1}}});
  await t.test("Gel métier, accès de contrôle ciblé et retrait d’accès",async()=>{
   await assert.rejects(finance.saveFinanceForm("owner",{id:item.id,version:3,code:"FIN-F01",data:request}),/plus être modifiée/);
   await assert.rejects(docs.depositFinanceDocument("owner",{requirementId:req.id,version:1},"new.pdf",Buffer.from("%PDF-1.4")),/verrouillé/);
   await assert.rejects(reassignFinance("admin",{kind:"case",id:item.id,ownerId:"owner",version:3,targetId:"other",reason:"Transfert interdit"}),/contrôle est en cours/);
   assert.equal((await docs.readFinanceDocument("reviewer",doc.id)).document.id,doc.id);
   await assert.rejects(docs.readFinanceDocument("unassigned",doc.id),/inaccessible/);
   await assert.rejects(flow.controlledCase("admin",item.id),/réservé/);
   await db.user.update({where:{id:"reviewer"},data:{active:false}});await assert.rejects(docs.readFinanceDocument("reviewer",doc.id),/suspendu/);await db.user.update({where:{id:"reviewer"},data:{active:true}});
  });
  const decision=(user:string,version:number,action:string)=>flow.decideReview(user,{id:item.id,version,action,reason:"Motif de recette complet",checks});
  await t.test("Retour pour correction conserve le cliché et crée un nouveau cycle",async()=>{
   await assert.rejects(decision("validator",3,"VALIDATE"),/attribuée/);
   await assert.rejects(decision("owner",3,"CONTROL"),/attribuée/);
   await decision("reviewer",3,"RETURN");
   assert.equal((await finance.financeCase("owner",item.id)).status,"DRAFT");
   await assert.rejects(docs.readFinanceDocument("reviewer",doc.id),/inaccessible/);
   await finance.saveFinanceForm("owner",{id:item.id,version:4,code:"FIN-F01",data:{...request,requested:"80"}});
   await submit(5);
   assert.deepEqual((await db.financeReview.findUniqueOrThrow({where:{id:initial.id}})).snapshot,initial.snapshot);
   assert.equal(await db.financeReview.count({where:{caseId:item.id}}),2);
  });
  await t.test("Contrôle préalable, confirmations et décision unique",async()=>{
   await assert.rejects(flow.decideReview("reviewer",{id:item.id,version:6,action:"CONTROL",reason:"Motif détaillé",checks:{...checks,documents:false}}),/trois points/);
   await decision("reviewer",6,"CONTROL");
   await assert.rejects(decision("reviewer",7,"VALIDATE"),/attribuée/);
   const results=await Promise.allSettled([decision("validator",7,"VALIDATE"),decision("validator",7,"VALIDATE")]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);
   assert.equal((await finance.financeCase("owner",item.id)).status,"INTERNALLY_VALIDATED");
   assert.equal(await db.financeReviewEvent.count({where:{caseId:item.id,action:"VALIDATE"}}),1);
   await assert.rejects(decision("owner",8,"WITHDRAW"),/attribuée/);
   await assert.rejects(finance.saveFinanceForm("owner",{id:item.id,version:8,code:"FIN-F01",data:request}),/plus être modifiée/);
  });
  await t.test("Autorisation ciblée : destinataire, pièces, versions, gel et retrait",async()=>{
   const {saveAuthorization,changeAuthorization}=await import("../src/lib/authorizations");
   const {authorizationPeriod}=await import("../src/lib/authorization-model");
   const {saveInstitution}=await import("../src/lib/institutions");
   const institution=await saveInstitution("owner",{data:{name:"Institution cible",branch:"Agence",contactName:"",contactRole:"",email:"",phone:"",address:"Adresse initiale",notes:"Note interne secrète"}});
   const data={institutionId:institution.id,controllerEntity:"Kip-City fictif",recipientService:"Service financement",purpose:"Étude du financement fictif",scopes:["IDENTITY"],documentIds:[doc.id],startsOn:"2026-01-01",endsOn:"2099-12-31",endEvent:"Fin de l’étude",stopContact:"contact@test.invalid",noticeVersion:"Notice de recette v1"};
   const input={caseId:item.id,cycle:2,data};
   await assert.rejects(saveAuthorization("other",input),/attribué/);
   await assert.rejects(saveAuthorization("admin",input),/réservé/);
   await assert.rejects(saveAuthorization("owner",{...input,data:{...data,scopes:[]}}));
   await assert.rejects(saveAuthorization("owner",{...input,data:{...data,status:"SIGNED"}}));
   await assert.rejects(saveAuthorization("owner",{...input,cycle:1}),/actuelle/);
   await assert.rejects(saveAuthorization("owner",{...input,data:{...data,endsOn:"2025-01-01"}}));
   await assert.rejects(saveAuthorization("owner",{...input,data:{...data,documentIds:["outside-case"]}}),/version contrôlée/);
   const first=await saveAuthorization("owner",input);
   const stored=await db.financeAuthorization.findUniqueOrThrow({where:{id:first.id}});
   const serialized=JSON.stringify(stored.payload);
   assert.ok(!serialized.includes("Note interne secrète"));assert.ok(!serialized.includes("Revenus nets réguliers"));
   await db.financeInstitution.update({where:{id:institution.id},data:{address:"Nouvelle adresse"}});
   assert.ok(JSON.stringify((await db.financeAuthorization.findUniqueOrThrow({where:{id:first.id}})).payload).includes("Adresse initiale"));
   const changes=await Promise.allSettled([saveAuthorization("owner",{...input,id:first.id,version:1,data:{...data,purpose:"Nouvelle finalité explicite"}}),saveAuthorization("owner",{...input,id:first.id,version:1,data:{...data,purpose:"Autre finalité explicite"}})]);
   assert.equal(changes.filter(r=>r.status==="fulfilled").length,1);
   assert.equal((await db.financeAuthorizationRevision.findUniqueOrThrow({where:{authorizationId_version:{authorizationId:first.id,version:1}}})).status,"DRAFT");
   await changeAuthorization("owner",{id:first.id,version:2,action:"PREPARE",reason:"Contenu relu pour signature"});
   assert.equal((await db.financeAuthorization.findUniqueOrThrow({where:{id:first.id}})).status,"READY_FOR_SIGNATURE");
   await assert.rejects(saveAuthorization("owner",{...input,id:first.id,version:3}),/plus modifiable/);
   await assert.rejects(changeAuthorization("other",{id:first.id,version:3,action:"WITHDRAW",reason:"Retrait non autorisé"}),/inaccessible/);
   await changeAuthorization("owner",{id:first.id,version:3,action:"WITHDRAW",reason:"Demande fictive de retrait"});
   await assert.rejects(changeAuthorization("owner",{id:first.id,version:4,action:"PREPARE",reason:"Tentative de réactivation"}),/modifiée/);
   const expired=await saveAuthorization("owner",{...input,data:{...data,startsOn:"2020-01-01",endsOn:"2020-12-31"}});
   await assert.rejects(changeAuthorization("owner",{id:expired.id,version:1,action:"PREPARE",reason:"Ancienne période de test"}),/expirée/);
   assert.equal(authorizationPeriod({startsOn:"2026-01-01",endsOn:"2026-01-31"},"2026-01-31"),"Période en cours");
   assert.equal(authorizationPeriod({startsOn:"2026-01-01",endsOn:"2026-01-31"},"2026-02-01"),"Période expirée");
  });

  const {changeReopening}=await import("../src/lib/finance-reopening");
  const {notifications}=await import("../src/lib/notifications");
  const reopen=async(actor:string,action:string,version?:number)=>changeReopening(actor,{id:item.id,version:version??(await db.financeCase.findUniqueOrThrow({where:{id:item.id}})).version,action,reason:"Correction du budget demandée pour nouveau devis"});
  await t.test("Réouverture : demande motivée, rôles, annulation et refus",async()=>{
   await assert.rejects(reopen("other","REQUEST_REOPEN"),{status:403});
   await assert.rejects(reopen("validator","APPROVE_REOPEN"),{status:409});
   await assert.rejects(changeReopening("owner",{id:item.id,version:8,action:"REQUEST_REOPEN",reason:"court"}));
   await reopen("owner","REQUEST_REOPEN");
   const pending=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});
   assert.equal(pending.status,"INTERNALLY_VALIDATED");assert.ok(pending.reopeningRequestId);
   await assert.rejects(reopen("owner","REQUEST_REOPEN"),{status:409});
   await assert.rejects(reopen("owner","APPROVE_REOPEN"),{status:403});
   await assert.rejects(reopen("reviewer","APPROVE_REOPEN"),{status:403});
   assert.ok((await notifications("validator")).some(n=>n.id===`reopening:${pending.reopeningRequestId}`));
   assert.ok(!(await notifications("unassigned")).some(n=>n.id===`reopening:${pending.reopeningRequestId}`));
   await db.user.update({where:{id:"validator"},data:{active:false}});await assert.rejects(reopen("validator","APPROVE_REOPEN"),{status:403});await db.user.update({where:{id:"validator"},data:{active:true}});
   await db.user.update({where:{id:"validator"},data:{personId:"p1"}});await assert.rejects(reopen("validator","APPROVE_REOPEN"),{status:403});await db.user.update({where:{id:"validator"},data:{personId:"p4"}});
   await reopen("owner","CANCEL_REOPEN");
   assert.ok(!(await notifications("validator")).some(n=>n.id===`reopening:${pending.reopeningRequestId}`));
   await reopen("owner","REQUEST_REOPEN");await reopen("validator","REJECT_REOPEN");
   const rejected=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});assert.equal(rejected.status,"INTERNALLY_VALIDATED");assert.equal(rejected.reopeningRequestId,null);
   assert.ok((await notifications("owner")).some(n=>n.title==="Réouverture du dossier refusée"));
  });
  await t.test("Réouverture atomique retire les préparations et préserve les archives",async()=>{
   const {saveAuthorization,changeAuthorization}=await import("../src/lib/authorizations");
   const old=await db.financeAuthorization.findFirstOrThrow({where:{caseId:item.id}});
   const payload=old.payload as {input:Record<string,unknown>};
   const input={caseId:item.id,cycle:2,data:{...payload.input,startsOn:"2026-01-01",endsOn:"2099-12-31"}};
   const ready=await saveAuthorization("owner",input);await changeAuthorization("owner",{id:ready.id,version:1,action:"PREPARE",reason:"Préparation avant correction"});
   const draft=await saveAuthorization("owner",input);
   const frozen=await db.financeReview.findUniqueOrThrow({where:{caseId_cycle:{caseId:item.id,cycle:2}}});
   await reopen("owner","REQUEST_REOPEN");
   await assert.rejects(saveAuthorization("owner",input),{status:409});
   await assert.rejects(changeAuthorization("owner",{id:draft.id,version:1,action:"PREPARE",reason:"Préparation durant correction"}),{status:409});
   const version=(await db.financeCase.findUniqueOrThrow({where:{id:item.id}})).version;
   const results=await Promise.allSettled([reopen("validator","APPROVE_REOPEN",version),reopen("validator","APPROVE_REOPEN",version)]);
   assert.equal(results.filter(r=>r.status==="fulfilled").length,1);
   const current=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});assert.equal(current.status,"DRAFT");assert.equal(current.reopeningRequestId,null);assert.equal(current.reviewCycle,2);
   for(const a of [ready,draft])assert.equal((await db.financeAuthorization.findUniqueOrThrow({where:{id:a.id}})).status,"WITHDRAWN");
   assert.equal((await db.financeAuthorizationRevision.findUniqueOrThrow({where:{authorizationId_version:{authorizationId:ready.id,version:2}}})).status,"READY_FOR_SIGNATURE");
   assert.deepEqual((await db.financeReview.findUniqueOrThrow({where:{id:frozen.id}})).snapshot,frozen.snapshot);
   await assert.rejects(flow.controlledCase("validator",item.id),{status:404});
   await assert.rejects(changeAuthorization("owner",{id:ready.id,version:3,action:"PREPARE",reason:"Réutilisation ancienne autorisation"}),{status:409});
  });
  await t.test("Un dossier corrigé repasse par un nouveau contrôle distinct",async()=>{
   const current=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});
   await finance.saveFinanceForm("owner",{id:item.id,version:current.version,code:"FIN-F01",data:{...request,requested:"75"}});
   await submit(current.version+1);
   const revised=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});assert.equal(revised.reviewCycle,3);assert.equal(revised.status,"IN_REVIEW");
   await assert.rejects(decision("validator",revised.version,"VALIDATE"),{status:403});
   await decision("reviewer",revised.version,"CONTROL");await decision("validator",revised.version+1,"VALIDATE");
   assert.equal(await db.financeReview.count({where:{caseId:item.id}}),3);
   assert.equal(await db.financeReviewEvent.count({where:{caseId:item.id,action:"APPROVE_REOPEN"}}),1);
  });

  const {replaceValidator}=await import("../src/lib/assignments");
  const replace=async(targetId:string,actorId="admin",version?:number)=>replaceValidator(actorId,{id:item.id,version:version??(await db.financeCase.findUniqueOrThrow({where:{id:item.id}})).version,targetId,reason:"Validateur indisponible, continuité du traitement"});
  await t.test("Remplacement : administration et indépendance de la personne",async()=>{
   for(const [id,personId] of [["replacement","p10"],["prep-alias","p1"],["control-alias","p3"],["admin-alias","p6"]])await db.user.create({data:{id,personId,role:"FINANCE_VALIDATOR",name:id,email:`${id}@test.invalid`}});
   await assert.rejects(replace("replacement"),{status:409});
   await reopen("owner","REQUEST_REOPEN");
   await assert.rejects(replace("replacement","owner"),{status:403});
   await assert.rejects(replace("replacement","validator"),{status:403});
   await assert.rejects(replace("reviewer"),{status:409});
   for(const target of ["prep-alias","control-alias","admin-alias"])await assert.rejects(replace(target),{status:403});
   await db.user.update({where:{id:"replacement"},data:{active:false}});await assert.rejects(replace("replacement"),{status:409});await db.user.update({where:{id:"replacement"},data:{active:true}});
   await db.user.update({where:{id:"admin"},data:{active:false}});await assert.rejects(replace("replacement"),{status:403});await db.user.update({where:{id:"admin"},data:{active:true}});
  });
  await t.test("Remplacement concurrent : retrait d’accès, notification transférée et archives intactes",async()=>{
   const current=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});
   const frozen=await db.financeReview.findUniqueOrThrow({where:{caseId_cycle:{caseId:item.id,cycle:current.reviewCycle}}});
   await db.user.update({where:{id:"validator"},data:{active:false}});
   const races=await Promise.allSettled([replace("replacement","admin",current.version),replace("replacement","admin",current.version)]);assert.equal(races.filter(r=>r.status==="fulfilled").length,1);
   await db.user.update({where:{id:"validator"},data:{active:true}});
   const changed=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});assert.equal(changed.validatorId,"replacement");assert.equal(changed.status,"INTERNALLY_VALIDATED");assert.equal(changed.reopeningRequestId,current.reopeningRequestId);
   await assert.rejects(flow.controlledCase("validator",item.id),{status:404});await assert.rejects(docs.readFinanceDocument("validator",doc.id),{status:404});
   await assert.rejects(reopen("validator","APPROVE_REOPEN"),{status:403});
   assert.equal((await flow.controlledCase("replacement",item.id)).id,item.id);assert.equal((await docs.readFinanceDocument("replacement",doc.id)).document.id,doc.id);
   assert.ok(!(await notifications("validator")).some(n=>n.id===`reopening:${current.reopeningRequestId}`));assert.ok((await notifications("replacement")).some(n=>n.id===`reopening:${current.reopeningRequestId}`));
   assert.deepEqual((await db.financeReview.findUniqueOrThrow({where:{id:frozen.id}})).snapshot,frozen.snapshot);
   assert.equal(await db.auditEvent.count({where:{objectId:item.id,action:"FINANCE_VALIDATOR_REASSIGNED"}}),1);
   await reopen("replacement","APPROVE_REOPEN");
   await assert.rejects(replace("validator"),{status:409});
  });
  await t.test("Remplacement pendant la validation conserve le contrôle et exige une décision",async()=>{
   const draft=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});await submit(draft.version);await assert.rejects(replace("replacement"),{status:409});
   const pending=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});await decision("reviewer",pending.version,"CONTROL");
   await replace("replacement");
   const changed=await db.financeCase.findUniqueOrThrow({where:{id:item.id}});assert.equal(changed.status,"IN_VALIDATION");
   await assert.rejects(decision("validator",changed.version,"VALIDATE"),{status:403});
   await decision("replacement",changed.version,"VALIDATE");
   assert.equal((await db.financeCase.findUniqueOrThrow({where:{id:item.id}})).status,"INTERNALLY_VALIDATED");
  });
 }finally{await db.$disconnect();rmSync(root,{recursive:true,force:true});}
});
