import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {pageActor} from "@/lib/session";
import {homeForRole} from "@/lib/roles";
import {WorkflowError} from "@/lib/workflow";
import {publicationHistory,comparePublicationVersions} from "@/lib/publication-history";
import {publicationAudiences,publicationStates} from "@/lib/publication-model";
import {Shell,Heading} from "@/components/shell";
export default async function Versions({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{before?:string;after?:string}>}){
 const actor=await pageActor();if(actor.role!=="ACQUIRER_AGENT")redirect(homeForRole(actor.role));const {id}=await params,query=await searchParams;
 const history=await publicationHistory(actor.id,id).catch(e=>{if(e instanceof WorkflowError&&e.status===404)notFound();throw e;});
 let comparison;try{comparison=comparePublicationVersions(history.versions,query.before,query.after);}catch(e){if(e instanceof WorkflowError&&e.status===404)notFound();throw e;}
 const fields={title:"Titre",body:"Texte",audience:"Destinataires",attachments:"Fichiers joints",status:"Statut"};
 return <Shell staff name={actor.name}><Link className="text-link" href={`/gestion/publications/${id}`}>← Revenir à la publication</Link><Heading eyebrow="HISTORIQUE" title="Comparer les versions" description={history.item.title}/>{comparison?<><section className="panel"><form className="form-grid">{([["before","Version de référence",comparison.left.version],["after","Version à comparer",comparison.right.version]] as const).map(([name,label,selected])=><label key={name}>{label}<select name={name} defaultValue={selected}>{history.versions.map(v=><option key={v.version} value={v.version}>Version {v.version} · {publicationStates[v.status]??v.status} · {new Date(v.date).toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</option>)}</select></label>)}<button className="button">Comparer</button></form><p className="profile-help">{Object.values(comparison.changes).some(Boolean)?`Éléments différents : ${Object.entries(fields).filter(([key])=>comparison.changes[key as keyof typeof fields]).map(([,label])=>label.toLowerCase()).join(", ")}.`:"Aucune différence de contenu, de destinataires, de fichiers ou de statut."}</p></section><div className="version-comparison">{[comparison.left,comparison.right].map((v,i)=><section className="panel" key={i}><h2>{i===0?"Référence":"Comparaison"} · Version {v.version}</h2><p className="muted small">{v.actor} · {new Date(v.date).toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</p><div className={comparison.changes.status?"version-changed":""}><strong>Statut</strong><p>{publicationStates[v.status]??v.status}</p></div><div className={comparison.changes.title?"version-changed":""}><strong>Titre</strong><h3>{v.content.title}</h3></div><div className={comparison.changes.audience?"version-changed":""}><strong>Destinataires</strong><p>{publicationAudiences[v.content.audience]}{v.content.targetReference?` · ${v.content.targetReference}`:""}</p></div><div className={comparison.changes.body?"version-changed":""}><strong>Texte</strong><p className="publication-body">{v.content.body}</p></div><div className={comparison.changes.attachments?"version-changed":""}><strong>Photos et documents ({v.attachments.length})</strong>{v.attachments.map(f=><article key={f.id} className="review-card"><p>{f.caption}</p>{f.takenOn&&<p className="muted small">Prise de vue : {f.takenOn.split("-").reverse().join("/")}</p>}<a className="text-link" href={`/api/publication-attachments/${f.id}?archive=1&download=1`}>{f.name} ↓</a></article>)}{!v.attachments.length&&<p>Aucun fichier dans cette version.</p>}</div></section>)}</div></>:<section className="panel"><p>Aucune version archivée exploitable pour cette publication.</p></section>}</Shell>;
}
