import {MemberDossierSelector} from "@/components/member-dossier-selector";
import { homeForRole } from "@/lib/roles";
import { Conversation } from "@/components/conversation";
import { pageActor } from "@/lib/session";
import { ownFile } from "@/lib/workflow";
import { Shell,Heading } from "@/components/shell";
import { notFound,redirect } from "next/navigation";
import { FileText,Download } from "lucide-react";
export default async function Section({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{messages?:string;dossier?:string}>}){const actor=await pageActor();if(actor.role!=="ACQUIRER")redirect(homeForRole(actor.role));const file=await ownFile(actor.id,(await searchParams).dossier);const section=(await params).section;if(!["documents","services","contact"].includes(section))notFound();const approved=file.declarations.some(p=>p.status==="APPROVED");const title=section==="documents"?"Mes documents":section==="services"?"Mes services":"Contact";if(section==="contact")return <Shell name={actor.name}><MemberDossierSelector userId={actor.id} fileId={file.id}/><Heading eyebrow="MYKIPCITY" title="Contact"/><Conversation fileId={file.id} userId={actor.id} page={Number((await searchParams).messages)||1}/></Shell>;return <Shell name={actor.name}><Heading eyebrow="MYKIPCITY" title={title} /><section className="panel">{section==="documents"?<>{file.documents.map(doc=><a href={`/api/documents/${doc.id}`} key={doc.id} className="document-row"><FileText size={20}/><span><strong>{doc.originalName}</strong><small>{Math.ceil(doc.size/1024)} Ko · Examen manuel requis</small></span><Download size={16}/></a>)}{!file.documents.length&&<p className="empty-text">Aucune pièce déposée.</p>}<a href="/mon-dossier" className="text-link">Accéder au dépôt des contrats →</a></>:<><h2>{approved?"Aucun service ouvert pour le moment":"Vos services après vérification"}</h2><p className="muted">{approved?"Aucun service disponible pour votre dossier.":"Un rattachement doit être validé avant l’ouverture éventuelle de services. Continuez votre dossier pour permettre son examen."}</p><a className="text-link" href="/mon-dossier">Consulter mon dossier →</a></>}</section></Shell>;}
