import Link from "next/link";
import {redirect} from "next/navigation";
import {db} from "@/lib/db";
import {pageActor} from "@/lib/session";
import {homeForRole} from "@/lib/roles";
import {Shell,Heading} from "@/components/shell";
import {ReviewerAssignmentForm} from "@/components/reviewer-assignment-form";
export default async function Reviewers({searchParams}:{searchParams:Promise<{q?:string;page?:string}>}){
 const actor=await pageActor();if(actor.role!=="ADMIN")redirect(homeForRole(actor.role));
 const params=await searchParams,q=(params.q??"").trim().slice(0,120),page=Math.max(1,Math.min(10000,Math.floor(Number(params.page))||1));
 const where={reference:{contains:q},status:"IN_REVIEW"};
 const [cases,count,users]=await Promise.all([db.financeCase.findMany({where,select:{id:true,reference:true,version:true,reviewCycle:true,ownerId:true,validatorId:true,reviewerId:true,reopeningRequestId:true},orderBy:[{updatedAt:"desc"},{id:"asc"}],skip:(page-1)*20,take:20}),db.financeCase.count({where}),db.user.findMany({where:{role:{in:["ADMIN","FINANCE_OFFICER","FINANCE_REVIEWER","FINANCE_VALIDATOR"]}},select:{id:true,name:true,role:true,personId:true,active:true}})]);
 const [reviews,events,audits]=await Promise.all([db.financeReview.findMany({where:{caseId:{in:cases.map(c=>c.id)}},select:{caseId:true,cycle:true,preparerPeople:true}}),db.financeReviewEvent.findMany({where:{caseId:{in:cases.map(c=>c.id)},action:{in:["CONTROL","REQUEST_REOPEN"]}},select:{caseId:true,cycle:true,actorPersonId:true}}),db.auditEvent.findMany({where:{action:"FINANCE_REVIEWER_REASSIGNED",objectId:{in:cases.map(c=>c.id)}},orderBy:{createdAt:"desc"},take:50})]);
 const url=(p:number)=>`?q=${encodeURIComponent(q)}&page=${p}`;
 return <Shell name={actor.name} admin><Link href="/administration/affectations" className="text-link">← Affectations Finance</Link><Heading eyebrow="ADMINISTRATION" title="Remplacement des contrôleurs"/><section className="panel"><form className="form-grid"><label>Référence du dossier<input name="q" defaultValue={q} maxLength={120}/></label><button className="button">Rechercher</button></form></section><section className="panel"><h2>Décisions en attente ({count})</h2>{cases.map(c=>{const current=users.find(u=>u.id===c.reviewerId);const review=reviews.find(r=>r.caseId===c.id&&r.cycle===c.reviewCycle);const excluded=new Set([...(review?.preparerPeople as string[]??[]),...users.filter(u=>[actor.id,c.ownerId,c.validatorId].includes(u.id)).map(u=>u.personId),...events.filter(e=>e.caseId===c.id&&e.cycle===c.reviewCycle).map(e=>e.actorPersonId)]);const choices=users.filter(u=>u.role==="FINANCE_REVIEWER"&&u.active&&u.id!==c.reviewerId&&!excluded.has(u.personId));return <article className="review-card" key={`${c.id}-${c.version}`}><h3>{c.reference}</h3><span className="status">{c.reopeningRequestId?"Réouverture demandée":"Contrôle en attente"}</span><p>Contrôleur : {current?.name??"Non attribué"}{current&&!current.active?" · Accès suspendu":""}</p><ReviewerAssignmentForm id={c.id} version={c.version} choices={choices}/></article>;})}{!cases.length&&<p>Aucune décision en attente.</p>}<div className="actions">{page>1&&<Link href={url(page-1)}>Précédent</Link>}{page*20<count&&<Link href={url(page+1)}>Suivant</Link>}</div></section><section className="panel"><h2>Derniers remplacements</h2><p className="muted small">Pour les dossiers affichés, jusqu’à 50 changements.</p>{audits.map(a=>{const d=JSON.parse(a.detail);return <article className="review-card" key={a.id}><h3>{d.label}</h3><p>{d.previousName} → {d.targetName}</p><p>{d.reason}</p><small>{users.find(u=>u.id===a.actorId)?.name??"Administrateur"} · {a.createdAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</small></article>;})}{!audits.length&&<p>Aucun remplacement.</p>}</section></Shell>;
}
