import Link from "next/link";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { pageActor } from "@/lib/session";
import { homeForRole } from "@/lib/roles";
import { Shell, Heading } from "@/components/shell";
import { AssignmentForm } from "@/components/assignment-form";
export default async function Assignments({ searchParams }: { searchParams: Promise<{ kind?: string; q?: string; owner?: string; page?: string }> }) {
  const actor = await pageActor(); if (actor.role !== "ADMIN") redirect(homeForRole(actor.role));
  const params = await searchParams; const kind = params.kind === "institution" ? "institution" : "case";
  const q = (params.q ?? "").trim().slice(0, 120), owner = params.owner ?? "";
  const page = Math.max(1, Math.min(10000, Math.floor(Number(params.page)) || 1));
  const owners = await db.user.findMany({ where: { role: "FINANCE_OFFICER" }, select: { id: true, name: true, email: true, active: true }, orderBy: { name: "asc" } });
  const referents = owners.filter(r => r.active);
  const caseWhere = { ...(owner ? { ownerId: owner } : {}), reference: { contains: q } };
  const institutionWhere = { ...(owner ? { ownerId: owner } : {}), OR: [{ name: { contains: q } }, { branch: { contains: q } }] };
  const selection = { id: true, ownerId: true, version: true, owner: { select: { name: true, active: true } } } as const;
  const rows = kind === "case" ? (await db.financeCase.findMany({ where: caseWhere, select: { ...selection, reference: true }, orderBy: { id: "asc" }, take: 20, skip: (page - 1) * 20 })).map(r => ({ ...r, label: r.reference })) : (await db.financeInstitution.findMany({ where: institutionWhere, select: { ...selection, name: true, branch: true }, orderBy: { id: "asc" }, take: 20, skip: (page - 1) * 20 })).map(r => ({ ...r, label: [r.name, r.branch].filter(Boolean).join(" · ") }));
  const count = kind === "case" ? await db.financeCase.count({ where: caseWhere }) : await db.financeInstitution.count({ where: institutionWhere });
  const events = await db.auditEvent.findMany({ where: { objectId: { in: rows.map(r => r.id) }, action: { in: ["FINANCE_CASE_REASSIGNED", "FINANCE_INSTITUTION_REASSIGNED"] } }, orderBy: { createdAt: "desc" }, take: 50 });
  const authors = await db.user.findMany({ where: { id: { in: events.map(e => e.actorId) } }, select: { id: true, name: true } });
  const pageUrl = (p: number) => `?kind=${kind}&owner=${encodeURIComponent(owner)}&q=${encodeURIComponent(q)}&page=${p}`;
  return <Shell name={actor.name} admin><Heading eyebrow="ADMINISTRATION" title="Affectations Finance"/><nav className="finance-tabs" aria-label="Type d’affectation"><Link href="?kind=case" aria-current={kind === "case" ? "page" : undefined}>Dossiers</Link><Link href="?kind=institution" aria-current={kind === "institution" ? "page" : undefined}>Institutions</Link><Link href="/administration/affectations/juridique">Cabinet juridique</Link><Link href="/administration/affectations/controleurs">Contrôleurs</Link><Link href="/administration/affectations/validateurs">Validateurs</Link></nav><section className="panel"><form className="form-grid"><input type="hidden" name="kind" value={kind}/><label>Rechercher<input name="q" defaultValue={q} placeholder={kind === "case" ? "Référence du dossier" : "Institution ou agence"}/></label><label>Référent actuel<select name="owner" defaultValue={owner}><option value="">Tous les référents</option>{owners.map(r => <option key={r.id} value={r.id}>{r.name}{r.active ? "" : " · Suspendu"}</option>)}</select></label><button className="button">Rechercher</button></form></section><section className="panel"><h2>{kind === "case" ? "Dossiers à attribuer" : "Répertoire des institutions"} ({count})</h2><p className="muted">{kind === "case" ? "Le nouveau référent aura accès au dossier, à ses pièces et à ses offres. L’ancien référent perdra cet accès." : "Le transfert porte sur la fiche institution. Les dossiers et leurs offres conservent leurs responsables."}</p>{rows.map(row => <article className="review-card" key={`${row.id}-${row.version}`}><h3>{row.label}</h3><p>Référent : {row.owner.name}{row.owner.active ? "" : " · Accès suspendu"}</p><AssignmentForm kind={kind} id={row.id} ownerId={row.ownerId} version={row.version} referents={referents}/></article>)}{!rows.length && <p>Aucun résultat.</p>}<div className="actions">{page > 1 && <Link href={pageUrl(page - 1)}>Précédent</Link>}{page * 20 < count && <Link href={pageUrl(page + 1)}>Suivant</Link>}</div></section><section className="panel"><h2>Dernières réattributions</h2><p className="muted">Pour les éléments affichés, jusqu’à 50 changements.</p>{events.map(event => { const detail = JSON.parse(event.detail); return <article key={event.id} className="review-card"><h3>{detail.label}</h3><p>{detail.previousName} → {detail.targetName}</p><p>{detail.reason}</p><small>{event.createdAt.toLocaleString("fr-FR", { timeZone: "Africa/Kinshasa" })} · {authors.find(a => a.id === event.actorId)?.name ?? "Administrateur"}</small></article>; })}{!events.length && <p>Aucune réattribution.</p>}</section></Shell>;
}
