import {MemberDossierSelector} from "@/components/member-dossier-selector";
import { ContractList } from "@/components/contract-list";
import { ContractUpload } from "@/components/contract-upload";
import { homeForRole } from "@/lib/roles";
import Link from "next/link";
import { pageActor } from "@/lib/session";
import { ownFile } from "@/lib/workflow";
import { Shell, Heading, Status } from "@/components/shell";
import { DossierForm, SubmitDossier } from "@/components/forms";
import { redirect } from "next/navigation";
import { LockKeyhole } from "lucide-react";
export default async function Dossier({searchParams}:{searchParams:Promise<{dossier?:string}>}){const actor=await pageActor();if(actor.role!=="ACQUIRER")redirect(homeForRole(actor.role));const file=await ownFile(actor.id,(await searchParams).dossier);const editable=["DRAFT","NEEDS_INFO"].includes(file.status);return <Shell name={actor.name}><MemberDossierSelector userId={actor.id} fileId={file.id}/><Heading eyebrow="PARCOURS ACQUÉREUR" title="Constituer mon dossier"><Status value={file.status}/></Heading><div className="steps"><span className="done">01 Compte créé</span><span className={editable?"current":"done"}>02 Dossier et contrats</span><span className={file.status==="SUBMITTED"?"current":""}>03 Vérification</span><span className={file.declarations.some(p=>p.status==="APPROVED")?"done":""}>04 Mon espace</span></div>{file.declarations.some(p=>p.reason)&&<div className="notice"><strong>Retour de l’équipe</strong>{file.declarations.filter(p=>p.reason).map(p=><p key={p.id}>{p.reference} : {p.reason}</p>)}</div>}<div className="content-grid"><section className="panel"><div className="panel-heading"><span className="section-number">01</span><div><h2>Mes informations</h2></div></div><DossierForm key={`${file.id}-${file.version}`} editable={editable} initial={{fileId:file.id,version:file.version,details:file.details,fullName:file.fullName,phone:file.phone,country:file.country,city:file.city,parcels:file.declarations.map(p=>({reference:p.reference,contractNumber:p.contractNumber,status:p.status,details:p.details}))}}/></section><div className="stack"><section className="panel"><div className="panel-heading"><span className="section-number">02</span><div><h2>Mes contrats</h2></div></div><ContractList fileId={file.id} documents={file.documents} version={file.version} editable={editable} parcels={file.declarations}/>{editable&&<ContractUpload fileId={file.id} key={`${file.id}-${file.version}`} version={file.version}/>}<p className="privacy-note"><LockKeyhole size={14}/>Accès limité à votre dossier et à l’équipe habilitée.</p></section><section className="panel"><div className="panel-heading"><span className="section-number">03</span><div><h2>Transmettre mon dossier</h2></div></div>{editable?<SubmitDossier fileId={file.id} version={file.version} enabled={!!file.declarations.length}/>:<><Status value={file.status}/><p className="muted">Vos déclarations enregistrées sont consultables ici. Les décisions apparaissent dans votre espace.</p><Link className="text-link" href="/mykipcity">Consulter mon espace →</Link></>}</section></div></div></Shell>;}
