"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
export type ChangeFileOption={id:string;label:string;proofs:{id:string;name:string}[];declarations:{id:string;label:string}[]};
async function command(input:unknown){const r=await fetch("/api/acquirer-changes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const data=await r.json();if(!r.ok)throw new Error(data.error??"Opération impossible.");return data;}
export function AcquirerChangeForm({files}:{files:ChangeFileOption[]}){
 const router=useRouter(),[kind,setKind]=useState("CONSOLIDATE"),[source,setSource]=useState(""),[target,setTarget]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setPending(true);setError("");setSuccess("");try{await command({action:"prepare",kind,sourceFileId:source,targetFileId:target,sourceProofId:data.get("sourceProofId"),targetProofId:data.get("targetProofId"),...(kind==="TRANSFER"?{sourceDeclarationId:data.get("sourceDeclarationId"),targetDeclarationId:data.get("targetDeclarationId")} : {}),reason:data.get("reason"),checked:data.get("checked")==="on"});setSuccess("Demande enregistrée. Une autre personne doit maintenant examiner les preuves et décider.");form.reset();setSource("");setTarget("");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Demande impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending} className="form-stack"><label>Opération<select value={kind} onChange={e=>setKind(e.target.value)}><option value="CONSOLIDATE">Regrouper les dossiers d’une même personne</option><option value="TRANSFER">Remplacer le titulaire de l’accès à une parcelle</option></select></label><p>{kind==="CONSOLIDATE"?"Tous les dossiers du compte d’origine seront accessibles depuis le compte conservé. Les pièces, conversations et références resteront dans leurs dossiers. Le compte d’origine sera désactivé et les deux comptes devront se reconnecter.":"Le contrôle retirera l’ancien accès et validera le nouveau rattachement. Chaque personne conservera ses propres dossiers et documents. Cette opération ne constitue pas un transfert de propriété."}</p>{(["source","target"] as const).map(side=>{const id=side==="source"?source:target;const file=files.find(f=>f.id===id);return <fieldset className="form-stack" key={side}><legend>{side==="source"?"Dossier d’origine":"Dossier du compte à conserver / nouveau titulaire"}</legend><label>Dossier<select required value={id} onChange={e=>(side==="source"?setSource:setTarget)(e.target.value)}><option value="">Choisir un dossier</option>{files.map(f=><option key={f.id} value={f.id} disabled={f.id===(side==="source"?target:source)}>{f.label}</option>)}</select></label><label>Preuve examinée<select key={id} required name={`${side}ProofId`} defaultValue=""><option value="">Choisir la pièce</option>{file?.proofs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{kind==="TRANSFER"&&<label>Déclaration de parcelle<select required key={`${id}-parcel`} name={`${side}DeclarationId`} defaultValue=""><option value="">Choisir</option>{file?.declarations.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>}</fieldset>;})}<label>Motif et référence de l’examen<textarea name="reason" minLength={15} maxLength={1500} required rows={3}/></label><label className="check-label"><input type="checkbox" required name="checked"/>{kind==="CONSOLIDATE"?"J’ai vérifié dans les deux dossiers qu’il s’agit de la même personne et confirmé avec elle le compte à conserver.":"J’ai examiné les pièces contractuelles des deux dossiers et la fin des droits du titulaire précédent."}</label></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}{success&&<p className="feedback success" role="status">{success}</p>}<button className="button" disabled={pending}>Soumettre au second agent</button></form>;
}
export function AcquirerChangeDecision({id,author,independent}:{id:string;author:boolean;independent:boolean}){
 const router=useRouter(),[pending,setPending]=useState(false),[error,setError]=useState("");
 if(!author&&!independent)return <p className="muted">Une autre personne de l’équipe doit prendre cette décision.</p>;
 return <form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);setError("");try{await command({action:"decide",id,decision:f.get("decision"),reason:f.get("reason"),checked:f.get("checked")==="on"});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Décision impossible.");}finally{setPending(false);}}}><fieldset disabled={pending}><label>Décision<select name="decision">{author?<option value="CANCEL">Retirer ma demande</option>:<><option value="REJECT">Refuser et demander un nouvel examen</option><option value="APPROVE">Approuver et appliquer</option></>}</select></label><label>Motif<textarea name="reason" minLength={15} maxLength={1500} required/></label><label className="check-label"><input type="checkbox" name="checked" required/>{author?"Je confirme le retrait de cette demande.":"J’ai vérifié les deux preuves, les dossiers concernés et les conséquences de ma décision."}</label></fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}<button className="button" disabled={pending}>Enregistrer la décision</button></form>;
}
export function DossierSelector({files,current}:{files:{id:string;label:string}[];current:string}){
 const router=useRouter(),[pending,setPending]=useState(false),[error,setError]=useState("");
 if(files.length<2)return null;
 return <form className="filters" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);setError("");try{await command({action:"select",fileId:data.get("fileId")});router.push("/mykipcity");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Sélection impossible.");}finally{setPending(false);}}}><label>Dossier consulté<select key={current} name="fileId" defaultValue={current} disabled={pending}>{files.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><button className="button secondary compact" disabled={pending}>Ouvrir ce dossier</button>{error&&<p role="alert">{error}</p>}</form>;
}
