"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { informationScopes,type AuthorizationInput } from "@/lib/authorization-model";
async function post(action:string,input:unknown){const res=await fetch(`/api/finance/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const result=await res.json();if(!res.ok)throw new Error(result.error??"Enregistrement impossible.");return result;}
export function AuthorizationForm({caseId,cycle,institutions,documents,id,version,initial}:{caseId:string;cycle:number;institutions:{id:string;name:string;branch:string}[];documents:{id:string;name:string;revision:number}[];id?:string;version?:number;initial?:AuthorizationInput}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const data={...Object.fromEntries(form),scopes:form.getAll("scopes"),documentIds:form.getAll("documentIds")};setPending(true);setError("");try{const result=await post("authorization",{caseId,cycle,id,version,data});router.push(`/finance/${caseId}/autorisations/${result.id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid"><label>Entité Kip-City responsable<input name="controllerEntity" required minLength={2} maxLength={200} defaultValue={initial?.controllerEntity}/></label><label>Institution destinataire<select name="institutionId" required defaultValue={initial?.institutionId??""}><option value="">Choisir une institution</option>{institutions.map(i=><option value={i.id} key={i.id}>{i.name}{i.branch?` · ${i.branch}`:""}</option>)}</select></label><label className="wide">Service ou personne destinataire<input name="recipientService" required minLength={2} maxLength={200} defaultValue={initial?.recipientService}/></label><label className="wide">Finalité et financement examiné<textarea name="purpose" required minLength={10} maxLength={2000} defaultValue={initial?.purpose}/></label></div><h3>Informations proposées au partage</h3><div className="form-stack">{Object.entries(informationScopes).map(([key,label])=><label className="check-label" key={key}><input type="checkbox" name="scopes" value={key} defaultChecked={initial?.scopes.includes(key as keyof typeof informationScopes)??false}/><span>{label}</span></label>)}</div><h3>Pièces et versions</h3><div className="form-stack">{documents.map(d=><label className="check-label" key={d.id}><input type="checkbox" name="documentIds" value={d.id} defaultChecked={initial?.documentIds.includes(d.id)??false}/><span>{d.name} · Version {d.revision}</span></label>)}</div><div className="form-grid"><label>Début de période<input name="startsOn" type="date" required defaultValue={initial?.startsOn}/></label><label>Fin de période<input name="endsOn" type="date" required defaultValue={initial?.endsOn}/></label><label className="wide">Autre événement mettant fin à l’autorisation<input name="endEvent" maxLength={500} defaultValue={initial?.endEvent}/></label><label className="wide">Contact pour correction ou arrêt des envois<input name="stopContact" required minLength={5} maxLength={300} defaultValue={initial?.stopContact}/></label><label className="wide">Référence et version de la notice<input name="noticeVersion" required maxLength={160} defaultValue={initial?.noticeVersion}/></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le brouillon"}</button></form>;
}
export function AuthorizationActions({id,version,status,prepareBlocked=false}:{id:string;version:number;status:string;prepareBlocked?:boolean}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{await post("authorization-state",{id,version,action:form.get("action"),reason:form.get("reason")});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Action impossible.");}finally{setPending(false);}}
 if(status==="WITHDRAWN")return null;
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-stack"><label>Action<select name="action" required defaultValue=""><option value="">Choisir</option>{status==="DRAFT"&&!prepareBlocked&&<option value="PREPARE">Figer pour signature</option>}<option value="WITHDRAW">Retirer cette autorisation</option></select></label><label>Motif<textarea name="reason" required minLength={10} maxLength={1000}/></label></div></fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}<button className="button" disabled={pending}>Confirmer</button></form>;
}
