import {FileText,Download} from "lucide-react";
import {contractGroups,type ContractPage} from "@/lib/contract-groups";
import {documentDetails} from "@/lib/dossier-model";
import {ContractDetails} from "./contract-details";
import {ContractSummary} from "./dossier-details";
import {ContractUpload} from "./contract-upload";
export function ContractList({documents,version,editable=false,parcels,fileId}:{fileId?:string;documents:ContractPage[];version:number;editable?:boolean;parcels:{reference:string;status:string}[]}){
 function pages(rows:ContractPage[]){return rows.map((doc,i)=><a key={doc.id} href={`/api/documents/${doc.id}`} className="document-row"><FileText size={20}/><span><strong>{rows.length>1?`${i+1}. `:""}{doc.originalName}</strong><small>{Math.ceil(doc.size/1024)} Ko</small></span><Download size={16}/></a>);}
 return <div className="document-list">{contractGroups(documents).map(group=>{const current=group.versions.find(v=>v.pages[0].isCurrent);if(!current)return null;const first=current.pages[0];const metadata=documentDetails.safeParse(first.details);const unlocked=!parcels.some(p=>p.status!=="PENDING"&&(!metadata.success||metadata.data.parcelReferences.includes(p.reference)));const canEdit=editable&&unlocked;return <article className="review-card" key={group.id}><h3>{first.originalName}</h3><p className="muted small">Version {current.revision} · {current.pages.length} fichier{current.pages.length>1?"s":""}</p>{pages(current.pages)}{editable?<ContractDetails key={`${first.id}-${version}`} id={first.id} version={version} initial={first.details} parcels={parcels.map(p=>p.reference)} editable={canEdit}/>:<ContractSummary value={first.details}/ >}{canEdit&&<details className="document-history"><summary>Remplacer cette pièce</summary><ContractUpload fileId={fileId} key={version} version={version} replaceId={first.id}/></details>}{group.versions.length>1&&<details className="document-history"><summary>Versions précédentes ({group.versions.length-1})</summary>{group.versions.filter(v=>!v.pages[0].isCurrent).map(v=><section className="review-card" key={v.revision}><h4>Version {v.revision} · Archivée</h4>{pages(v.pages)}<ContractSummary value={v.pages[0].details}/></section>)}</details>}</article>;})}{!documents.length&&<p className="empty-text">Aucune pièce déposée.</p>}</div>;
}
