"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
export function ContractUpload({version,replaceId,fileId}:{version:number;replaceId?:string;fileId?:string}){
 const router=useRouter();const[files,setFiles]=useState<File[]>([]),[token,setToken]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState("");
 function update(next:File[]){setFiles(next);setToken(crypto.randomUUID());setError("");}
 function move(index:number,delta:number){const next=[...files];[next[index],next[index+delta]]=[next[index+delta],next[index]];update(next);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!files.length)return;setPending(true);setError("");try{if(files.length>10||files.some(f=>f.size>20*1024*1024)||files.reduce((s,f)=>s+f.size,0)>200*1024*1024)throw new Error("10 fichiers maximum, 20 Mo par fichier et 200 Mo au total.");const body=new FormData();body.set("version",String(version));if(fileId)body.set("fileId",fileId);body.set("token",token);if(replaceId)body.set("replaceId",replaceId);for(const file of files)body.append("files",file);const r=await fetch("/api/documents/contract",{method:"POST",body});const result=await r.json();if(!r.ok)throw new Error(result.error??"Dépôt impossible.");setFiles([]);setToken("");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Dépôt impossible. Vous pouvez réessayer.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><label className="upload"><strong>{replaceId?"Nouvelle copie complète":"Ajouter une pièce complète"}</strong><span className="muted small">PDF, JPEG ou PNG · 10 fichiers maximum · 20 Mo par fichier · 200 Mo au total</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{update([...files,...Array.from(e.target.files??[])]);e.target.value="";}}/></label>{files.length>0&&<ol className="contract-file-order">{files.map((file,index)=><li key={index}><span>{index+1}. {file.name} · {Math.ceil(file.size/1024)} Ko</span><div className="actions"><button type="button" className="button secondary compact" disabled={index===0} aria-label={`Monter ${file.name}`} onClick={()=>move(index,-1)}>↑</button><button type="button" className="button secondary compact" disabled={index===files.length-1} aria-label={`Descendre ${file.name}`} onClick={()=>move(index,1)}>↓</button><button type="button" className="button secondary compact" onClick={()=>update(files.filter((_,i)=>i!==index))}>Retirer</button></div></li>)}</ol>}</fieldset><p className="muted small">Une pièce trop volumineuse ? Contactez l’équipe depuis Contact pour organiser sa transmission.</p>{replaceId&&<p className="muted small">Joignez toutes les pages, y compris celles qui ne changent pas. La version précédente sera conservée.</p>}{error&&<p role="alert" className="feedback error">{error}</p>}<button className="button" disabled={pending||!files.length}>{pending?"Dépôt en cours…":replaceId?"Déposer la nouvelle version":"Déposer la pièce"}</button></form>;
}
