import {ContactAssignment} from "./contact-assignment";
import Link from "next/link";
import { db } from "@/lib/db";
import { conversation,conversationPage } from "@/lib/management";
import { MessageForm } from "./forms";
import { ReadNotifications } from "./notification-actions";
export async function Conversation({fileId,userId,page=1}:{fileId:string;userId:string;page?:number}){
 const file=await conversation(userId,fileId);const result=await conversationPage(userId,fileId,page);
 const isMember=file.acquirer.userId===userId;
 const base=isMember?"/mykipcity/contact":`/gestion/acquereurs/${fileId}`;
 const [parcels,documents,receipts]=await Promise.all([
  db.parcelDeclaration.findMany({where:{fileId},select:{reference:true},orderBy:{reference:"asc"}}),
  db.memberDocumentVersion.findMany({where:{document:{fileId,...(isMember?{OR:[{direction:"REQUESTED"},{closedAt:null}]}:{})}},select:{id:true,originalName:true,revision:true,document:{select:{title:true}}},orderBy:{createdAt:"desc"},take:100}),
  db.notificationReceipt.findMany({where:{userId,notificationId:{in:result.messages.map(m=>`message:${m.id}`)}},select:{notificationId:true}}),
 ]);
 const contact=file.contactOwnerId?await db.user.findUnique({where:{id:file.contactOwnerId},select:{name:true,active:true,role:true}}):null;
 const choices=isMember?[]:await db.user.findMany({where:{role:"ACQUIRER_AGENT",active:true},select:{id:true,name:true},orderBy:{name:"asc"}});
 const changes=isMember?[]:await db.auditEvent.findMany({where:{objectId:fileId,action:"CONTACT_ASSIGNED"},orderBy:{createdAt:"desc"},take:10});
 const unread=result.messages.filter(m=>m.authorId!==userId&&(isMember||m.author.role==="ACQUIRER")&&!receipts.some(r=>r.notificationId===`message:${m.id}`));
 return <div className="conversation-layout"><section className="panel"><div className="section-title"><h2>Nos échanges</h2>{unread.length>0&&<ReadNotifications ids={unread.map(m=>`message:${m.id}`)} label="Marquer ces messages comme lus"/>}</div><div className="messages">{result.messages.length?result.messages.map(message=><article className={`message ${message.authorId===userId?"mine":""}`} key={message.id}><div><strong>{message.author.name}{message.author.role==="ACQUIRER_AGENT"?" · Kip-City":""}</strong><time dateTime={message.createdAt.toISOString()}>{message.createdAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa",dateStyle:"short",timeStyle:"short"})}</time></div>{message.subject&&<h3>{message.subject}</h3>}{message.parcelReference&&<p className="small muted">Parcelle {message.parcelReference}</p>}<p>{message.body}</p>{message.attachmentId&&<a className="text-link" href={`/api/member-documents/${message.attachmentId}`}>Document joint ↓</a>}{message.uploadStorageKey&&<a className="text-link" href={`/api/messages/${message.id}/file`}>{message.uploadName} · {Math.ceil((message.uploadSize??0)/1024)} Ko ↓</a>}{message.authorId===userId&&<p className="small muted">{message.readByRecipient?"Lu par le destinataire":"Envoyé"}</p>}</article>):<p className="empty-text">Écrivez à l’équipe pour commencer un échange.</p>}</div><div className="actions">{result.page>1&&<Link className="button secondary compact" href={`${base}?${isMember?`dossier=${fileId}&`:""}messages=${result.page-1}#echanges`}>Messages plus récents</Link>}{result.page*25<result.count&&<Link className="button secondary compact" href={`${base}?${isMember?`dossier=${fileId}&`:""}messages=${result.page+1}#echanges`}>Messages précédents</Link>}</div></section><section className="panel"><h2>Nouveau message</h2><p>Votre interlocuteur : {contact?.active&&contact.role==="ACQUIRER_AGENT"?contact.name:"Équipe Kip-City"}</p>{!isMember&&<><ContactAssignment key={file.contactVersion} fileId={fileId} version={file.contactVersion} ownerId={file.contactOwnerId} choices={choices}/><details><summary>Historique des affectations</summary>{changes.map(c=>{const d=JSON.parse(c.detail);return <p key={c.id}>{d.previousName} → {d.targetName} · {d.reason}<br/><small>{d.actorName} · {c.createdAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</small></p>;})}{!changes.length&&<p>Aucune affectation enregistrée.</p>}</details></>}<MessageForm key={fileId} fileId={fileId} parcels={parcels.map(p=>p.reference)} attachments={documents.map(d=>({id:d.id,label:`${d.document.title} · v${d.revision} · ${d.originalName}`}))}/><Link className="text-link profile-help" href={isMember?`/mykipcity/documents?dossier=${fileId}`:`/gestion/acquereurs/${fileId}/documents`}>Ouvrir les documents du dossier ↗</Link></section></div>;
}
