"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {qualities,readIdentity,readParcel,type IdentityDetails,type ParcelDetails} from "@/lib/dossier-model";
type Parcel={reference:string;contractNumber:string;status?:string;details?:unknown};
type Input={fileId?:string;version:number;fullName:string;phone:string;country:string;city:string;details?:unknown;parcels:Parcel[]};
export function DossierForm({initial,editable}:{initial:Input;editable:boolean}){
 const router=useRouter();const[identity,setIdentity]=useState(readIdentity(initial.details));
 const[parcels,setParcels]=useState((initial.parcels.length?initial.parcels:[{reference:"",contractNumber:""}]).map(p=>({...p,details:readParcel(p.details)})));
 const[pending,setPending]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const field=(key:keyof IdentityDetails,label:string,type="text")=><label key={key}>{label}<input type={type} value={String(identity[key])} maxLength={key==="address"?500:160} onChange={e=>setIdentity({...identity,[key]:e.target.value})}/></label>;
 function update(index:number,patch:Partial<(typeof parcels)[number]>){setParcels(parcels.map((p,i)=>i===index?{...p,...patch}:p));}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);setError("");setSuccess("");try{
  const fullName=[identity.lastName,identity.postName,identity.firstNames].filter(Boolean).join(" ")||initial.fullName;
  const r=await fetch("/api/workflow/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileId:initial.fileId,version:initial.version,fullName,phone:data.get("phone"),country:data.get("country"),city:data.get("city"),details:identity,parcels:parcels.map(({reference,contractNumber,details})=>({reference,contractNumber,details}))})});const result=await r.json();if(!r.ok)throw new Error(result.error);setSuccess("Votre brouillon est enregistré.");router.refresh();
 }catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form onSubmit={submit} className="form-stack"><fieldset disabled={!editable||pending} className="form-stack">
  <details open className="dossier-section"><summary>Mon identité</summary><div className="form-stack"><label>Ma qualité<select value={identity.quality} onChange={e=>setIdentity({...identity,quality:e.target.value as IdentityDetails["quality"]})}>{Object.entries(qualities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="form-grid">{field("lastName","Nom")}{field("postName","Postnom, si applicable")}{field("firstNames","Prénom(s), si applicable")}{field("holderName","Nom complet du titulaire au contrat")}</div><p className="small muted">Reprenez l’identité inscrite sur les pièces. Une représentation sera vérifiée par l’équipe.</p><details><summary>Informations complémentaires du contrat</summary><p className="small muted profile-help">Laissez vide ce qui n’est pas indiqué dans vos pièces.</p><div className="form-grid">{field("birthDate","Date de naissance","date")}{field("birthPlace","Lieu de naissance")}{field("nationality","Nationalité")}{field("profession","Profession")}{field("maritalStatus","État civil")}</div></details></div></details>
  <details open className="dossier-section"><summary>Mes coordonnées actuelles</summary><div className="form-grid"><label>Téléphone avec indicatif<input name="phone" type="tel" defaultValue={initial.phone} maxLength={30}/></label><label>Pays<input name="country" defaultValue={initial.country} maxLength={100}/></label><label>Ville<input name="city" defaultValue={initial.city} maxLength={100}/></label>{field("address","Adresse détaillée")}{field("region","Province ou région")}{field("postalCode","Code postal, si applicable")}<label>Contact préféré<select value={identity.contactPreference} onChange={e=>setIdentity({...identity,contactPreference:e.target.value as IdentityDetails["contactPreference"]})}><option value="EMAIL">E-mail</option><option value="PHONE">Téléphone</option></select></label><label className="wide">Observation sur mon identité ou mes coordonnées<textarea rows={2} maxLength={2000} value={identity.observation} onChange={e=>setIdentity({...identity,observation:e.target.value})}/></label></div></details>
  <div className="section-title"><h3>Mes parcelles</h3><span className="small muted">{parcels.length} / 10</span></div>
  {parcels.map((p,index)=>{const locked=Boolean(p.status&&p.status!=="PENDING");const detail=(key:keyof ParcelDetails,label:string)=><label key={key}>{label}<input value={String(p.details[key])} maxLength={key==="holders"?1000:300} onChange={e=>update(index,{details:{...p.details,[key]:e.target.value}})}/></label>;return <details className="dossier-section" open={parcels.length===1} key={index}><summary>{p.reference||`Parcelle ${index+1}`}{locked?" · Décision enregistrée":""}</summary><fieldset className="form-stack" disabled={locked}><label className="check-label"><input type="checkbox" checked={p.details.referenceUnknown} onChange={e=>update(index,{reference:e.target.checked?`A-IDENTIFIER-${crypto.randomUUID().slice(0,8).toUpperCase()}`:"",details:{...p.details,referenceUnknown:e.target.checked}})}/>Je ne connais pas la référence Kip-City</label>{!p.details.referenceUnknown&&<label>Référence Kip-City<input value={p.reference} onChange={e=>update(index,{reference:e.target.value})} required maxLength={60}/></label>}{p.details.referenceUnknown&&<p className="small muted">L’équipe rapprochera vos pièces du registre. Le repère ci-dessus sert uniquement au suivi de votre déclaration.</p>}<div className="form-grid"><label>Numéro du contrat<input value={p.contractNumber} maxLength={80} onChange={e=>update(index,{contractNumber:e.target.value})}/></label>{detail("cadastralReference","Référence cadastrale individuelle")}{detail("phase","Phase, si connue")}{detail("block","Bloc ou îlot")}{detail("location","Localisation")}{detail("area","Superficie indiquée (m²)")}{detail("dimensions","Dimensions indiquées (m)")}{detail("holders","Titulaire(s) indiqué(s) pour ce terrain")}<label>Ma relation à cette parcelle<select value={p.details.quality} onChange={e=>update(index,{details:{...p.details,quality:e.target.value as ParcelDetails["quality"]}})}>{Object.entries(qualities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><label className="check-label"><input type="checkbox" checked={p.details.missingContract} onChange={e=>update(index,{details:{...p.details,missingContract:e.target.checked}})}/>Je n’ai plus ma copie et je demande l’aide de Kip-City.</label><label>Observation sur cette parcelle<textarea rows={2} maxLength={2000} value={p.details.observation} onChange={e=>update(index,{details:{...p.details,observation:e.target.value}})}/></label>{editable&&parcels.length>1&&!locked&&<button type="button" className="button secondary compact" onClick={()=>setParcels(parcels.filter((_,i)=>i!==index))}>Retirer cette déclaration</button>}</fieldset></details>;})}
  {editable&&parcels.length<10&&<button type="button" className="button secondary compact" onClick={()=>setParcels([...parcels,{reference:"",contractNumber:"",details:readParcel(null)}])}>Ajouter une parcelle</button>}
 </fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}{success&&<p className="feedback success" role="status">{success}</p>}{editable&&<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer mon brouillon"}</button>}</form>;
}
