import { db } from "@/lib/db";
import { financeCase } from "@/lib/finance";
import { documentCategories,documentStates } from "@/lib/finance-document-model";
import { RequirementForm,FinanceDocumentUpload,FinanceDocumentReview,ShareRequirement } from "./finance-documents";
export async function FinanceDocumentList({caseId,userId}:{caseId:string;userId:string}){
 const item=await financeCase(userId,caseId);
 const requirements=await db.financeRequirement.findMany({where:{caseId},include:{documents:{orderBy:{revision:"desc"}}},orderBy:{createdAt:"asc"}});
 const missing=requirements.filter(r=>!r.documents.length||r.documents[0].status==="REJECTED").length;
 const pending=requirements.filter(r=>r.documents[0]?.status==="PENDING").length;
 const checked=requirements.filter(r=>r.documents[0]?.status==="ACCEPTED").length;
 return <><div className="stats"><article><span>À fournir ou remplacer</span><strong>{missing}</strong></article><article><span>À examiner</span><strong>{pending}</strong></article><article><span>Contrôlées</span><strong>{checked}</strong></article></div><div className="finance-layout"><div className="stack">{requirements.map(req=>{const latest=req.documents[0];return <section className="panel" key={req.id}><div className="section-title"><div><p className="eyebrow">{documentCategories[req.category as keyof typeof documentCategories]}</p><h2>{req.label}</h2></div><span className={`status ${latest?.status==="ACCEPTED"?"positive":""}`}>{latest?documentStates[latest.status as keyof typeof documentStates]:"À fournir"}</span></div>{latest&&<><a className="document-row text-link" href={`/api/finance/documents/${latest.id}`}>{latest.originalName} · v{latest.revision} · {Math.ceil(latest.size/1024)} Ko ↓</a>{latest.reviewedAt&&<p className="muted small">Contrôlée le {latest.reviewedAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa",dateStyle:"short",timeStyle:"short"})}</p>}{latest.reason&&<p className="review-observation">{latest.reason}</p>}{latest.status==="PENDING"&&item.status==="DRAFT"&&<FinanceDocumentReview id={latest.id}/>}</>}{item.status==="DRAFT"&&<FinanceDocumentUpload requirementId={req.id} version={req.version}/>}<ShareRequirement id={req.id} version={req.sharingVersion} shared={Boolean(req.sharedAt)} instructions={req.memberInstructions} locked={item.status!=="DRAFT"}/> {req.documents.length>1&&<details className="document-history"><summary>Versions précédentes ({req.documents.length-1})</summary>{req.documents.slice(1).map(doc=><article key={doc.id}><a className="text-link" href={`/api/finance/documents/${doc.id}`}>{doc.originalName} · v{doc.revision} ↓</a><p className="muted small">{documentStates[doc.status as keyof typeof documentStates]} · {doc.createdAt.toLocaleDateString("fr-FR",{timeZone:"Africa/Kinshasa"})}</p>{doc.reason&&<p>{doc.reason}</p>}</article>)}</details>}</section>;})}{!requirements.length&&<section className="panel"><p>Aucune pièce demandée.</p></section>}</div>{item.status==="DRAFT"&&<section className="panel"><h2>Ajouter une pièce attendue</h2><RequirementForm caseId={caseId}/><p className="muted small">Les nouvelles pièces restent internes jusqu’à la publication explicite de leur demande à l’acquéreur.</p></section>}</div></>;
}
