"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Plus,Trash2 } from "lucide-react";
import { currencies,pathways,qualities,needs,situations,categories,periods,proofs,summarizeBudget,money,type FinanceRequest,type FinanceBudget,type Category } from "@/lib/finance-model";
const emptyRequest:FinanceRequest={applicantName:"",quality:"CANDIDATE",acquirerReference:"",phone:"",email:"",pathway:"HABITAT",need:"HABITAT",otherNeed:"",project:"",description:"",calendar:"",projectCost:"",projectCurrency:"USD",contribution:"",contributionCurrency:"USD",requested:"",requestedCurrency:"USD",situation:"NONE",institution:"",contact:"",nextContact:"",initialDocuments:""};
async function submitFinance(action:string,body:unknown){const response=await fetch(`/api/finance/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Enregistrement impossible.");return result;}
function Options({values}:{values:Record<string,string>}){return Object.entries(values).map(([key,label])=><option key={key} value={key}>{label}</option>);}
function CurrencySelect({name,value}:{name:string;value:string}){return <select name={name} defaultValue={value} aria-label="Devise">{currencies.map(c=><option key={c}>{c}</option>)}</select>;}
export function RequestForm({initial=emptyRequest,id,version,readOnly=false}:{readOnly?:boolean;initial?:FinanceRequest;id?:string;version?:number}){
  const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const data=Object.fromEntries(new FormData(event.currentTarget));try{const result=await submitFinance(id?"save":"create",id?{id,version,code:"FIN-F01",data}:data);router.push(`/finance/${id??result.id}?saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
  return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending||readOnly}><h2>Demandeur</h2><div className="form-grid"><label className="wide">Nom ou dénomination<input name="applicantName" defaultValue={initial.applicantName} required minLength={2} maxLength={160}/></label><label>Qualité<select name="quality" defaultValue={initial.quality}><Options values={qualities}/></select></label><label>Référence acquéreur<input name="acquirerReference" defaultValue={initial.acquirerReference} maxLength={60}/></label><label>Téléphone<input name="phone" defaultValue={initial.phone} maxLength={30} type="tel"/></label><label>E-mail<input name="email" defaultValue={initial.email} type="email"/></label></div><h2>Projet et besoin</h2><div className="form-grid"><label>Parcours<select name="pathway" defaultValue={initial.pathway}><Options values={pathways}/></select></label><label>Besoin<select name="need" defaultValue={initial.need}><Options values={needs}/></select></label><label className="wide">Autre besoin à préciser<input name="otherNeed" defaultValue={initial.otherNeed} maxLength={300}/></label><label className="wide">Parcelles ou projet concerné<textarea name="project" defaultValue={initial.project} maxLength={1000} rows={2}/></label><label className="wide">Description<textarea name="description" defaultValue={initial.description} maxLength={4000} rows={3}/></label><label className="wide">Calendrier souhaité<input name="calendar" defaultValue={initial.calendar} maxLength={300}/></label></div><h2>Montants déclarés</h2>{([['projectCost','projectCurrency','Coût estimé du projet'],['contribution','contributionCurrency','Apport disponible'],['requested','requestedCurrency','Montant recherché']] as const).map(([field,unit,label])=><div className="money-field" key={field}><label>{label}<input name={field} defaultValue={initial[field]} inputMode="decimal" placeholder="0,00" maxLength={15}/></label><label>Devise<CurrencySelect name={unit} value={initial[unit]}/></label></div>)}<h2>Suivi</h2><div className="form-grid"><label className="wide">Situation bancaire<select name="situation" defaultValue={initial.situation}><Options values={situations}/></select></label><label>Institution éventuelle<input name="institution" defaultValue={initial.institution} maxLength={200}/></label><label>Interlocuteur<input name="contact" defaultValue={initial.contact} maxLength={200}/></label><label>Prochain contact<input name="nextContact" type="date" defaultValue={initial.nextContact}/></label><label className="wide">Pièces disponibles et références<textarea name="initialDocuments" defaultValue={initial.initialDocuments} maxLength={1500} rows={3}/></label></div></fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}{!readOnly&&<button disabled={pending} className="button">{pending?"Enregistrement…":"Enregistrer le brouillon"}</button>}</form>;
}
const emptyBudget:FinanceBudget={situationDate:"",dependents:0,lines:[],installmentSource:"",stressScenario:"",risks:"",analystNotes:""};
const newLine=(category:Category):FinanceBudget["lines"][number]=>({category,amount:"",currency:"USD",period:["WORKS","FEES","FINANCING","PROVISION","RESOURCES"].includes(category)?"ONCE":"MONTH",proof:"UNKNOWN",evidence:"",stability:""});
export function BudgetForm({initial=emptyBudget,id,version,readOnly=false}:{readOnly?:boolean;initial?:FinanceBudget;id:string;version:number}){
  const router=useRouter();const[lines,setLines]=useState(initial.lines.length?initial.lines:[newLine("REGULAR")]);const[pending,setPending]=useState(false);const[error,setError]=useState("");
  function patch(index:number,updates:Partial<FinanceBudget["lines"][number]>){setLines(lines.map((l,i)=>i===index?{...l,...updates}:l));}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const raw=Object.fromEntries(new FormData(event.currentTarget));const data={...raw,dependents:Number(raw.dependents),lines};try{await submitFinance("save",{id,version,code:"FIN-F02",data});router.push(`/finance/${id}?tab=budget&saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
  return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending||readOnly}><div className="form-grid"><label>Date de situation<input name="situationDate" type="date" defaultValue={initial.situationDate}/></label><label>Personnes à charge<input name="dependents" type="number" min={0} max={100} required defaultValue={initial.dependents}/></label></div><h2>Revenus, charges et budget du projet</h2><div className="budget-lines">{lines.map((line,index)=><section className="budget-line" key={index}><div className="section-title"><h3>Ligne {index+1}</h3>{lines.length>1&&<button type="button" className="icon-button" aria-label={`Retirer la ligne ${index+1}`} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}><Trash2 size={17}/></button>}</div><div className="form-grid"><label className="wide">Poste<select value={line.category} onChange={e=>{const category=e.target.value as Category;patch(index,{category,period:newLine(category).period});}}><Options values={categories}/></select></label><label>Montant<input inputMode="decimal" value={line.amount} onChange={e=>patch(index,{amount:e.target.value})} required maxLength={15} placeholder="0,00"/></label><label>Devise<select value={line.currency} onChange={e=>patch(index,{currency:e.target.value as typeof line.currency})}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>Période<select value={line.period} onChange={e=>patch(index,{period:e.target.value as typeof line.period})}><Options values={periods}/></select></label><label>État de la preuve<select value={line.proof} onChange={e=>patch(index,{proof:e.target.value as typeof line.proof})}><Options values={proofs}/></select></label><label className="wide">Référence du justificatif<input value={line.evidence} onChange={e=>patch(index,{evidence:e.target.value})} maxLength={500}/></label><label className="wide">Stabilité ou précision<input value={line.stability} onChange={e=>patch(index,{stability:e.target.value})} maxLength={500}/></label></div></section>)}</div>{lines.length<40&&<button type="button" className="button secondary compact" onClick={()=>setLines([...lines,newLine("WORKS")])}><Plus size={16}/>Ajouter un poste</button>}<div className="form-stack"><label>Source des conditions de la nouvelle échéance<textarea name="installmentSource" defaultValue={initial.installmentSource} maxLength={1500} rows={2}/></label><label>Scénario défavorable et sources de change<textarea name="stressScenario" defaultValue={initial.stressScenario} maxLength={2500} rows={3}/></label><label>Risques identifiés<textarea name="risks" defaultValue={initial.risks} maxLength={2500} rows={2}/></label><label>Notes de l’analyste<textarea name="analystNotes" defaultValue={initial.analystNotes} maxLength={4000} rows={3}/></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}{!readOnly&&<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le budget"}</button>}</form>;
}
export function BudgetSummary({budget}:{budget:FinanceBudget}){
  return <section className="panel"><h2>Synthèse du budget enregistré</h2>{summarizeBudget(budget).map(s=><div className="budget-summary" key={s.currency}><h3>{s.currency}</h3><dl><dt>Coûts renseignés du projet</dt><dd>{s.costProvided?money(s.cost,s.currency):"Non renseignés"}</dd><dt>Ressources renseignées</dt><dd>{s.resourcesProvided?money(s.resources,s.currency):"Non renseignées"}</dd><dt>Besoin à financer</dt><dd>{s.projectComplete?money(s.need>0n?s.need:0n,s.currency):"Budget à compléter"}</dd><dt>Reste mensuel</dt><dd>{s.monthlyComplete?money(s.remainder,s.currency):"Revenus, charges et échéances mensuels à compléter"}</dd></dl></div>)}<p className="muted small">Calculs par devise, sans conversion. Un montant inconnu reste à compléter ; un poste nul doit être saisi à zéro. Le reste mensuel ne constitue pas une décision de crédit.</p></section>;
}
