"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { documentCategories } from "@/lib/finance-document-model";
async function action(name:string,data:unknown){const r=await fetch(`/api/finance/${name}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error??"L’opération a échoué.");}
export function RequirementForm({caseId}:{caseId:string}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setPending(true);setError("");const values=Object.fromEntries(new FormData(form));try{await action("require-document",{caseId,...values});form.reset();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><label>Type de pièce<select name="category">{Object.entries(documentCategories).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Pièce attendue<input name="label" placeholder="Ex. Relevés de revenus des trois derniers mois" required minLength={2} maxLength={160}/></label>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>Ajouter à la liste</button></form>;
}
export function FinanceDocumentUpload({requirementId,version}:{requirementId:string;version:number}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 return <form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setPending(true);setError("");const data=new FormData(form);data.set("requirementId",requirementId);data.set("version",String(version));try{const r=await fetch("/api/finance/documents",{method:"POST",body:data});const result=await r.json();if(!r.ok)throw new Error(result.error);form.reset();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Dépôt impossible.");}finally{setPending(false);}}}><label>{version?"Déposer une nouvelle version":"Déposer la pièce"}<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required/></label><span className="muted small">PDF, JPEG ou PNG · 8 Mo maximum</span>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button secondary compact" disabled={pending}>{pending?"Dépôt…":"Enregistrer le fichier"}</button></form>;
}
export function FinanceDocumentReview({id}:{id:string}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 return <form className="form-stack review-form" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setPending(true);setError("");try{await action("review-document",{id,...data});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Contrôle impossible.");}finally{setPending(false);}}}><label>Résultat du contrôle<select name="decision"><option value="REJECTED">Demander un remplacement</option><option value="ACCEPTED">Pièce contrôlée</option></select></label><label>Résultat du contrôle — visible par l’acquéreur pour ses dépôts<textarea name="reason" rows={2} required minLength={5} maxLength={1500}/></label>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>Enregistrer le contrôle</button></form>;
}
export function ShareRequirement({id,version,shared,instructions,locked}:{id:string;version:number;shared:boolean;instructions:string;locked:boolean}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 return <form className="form-stack document-history" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);setError("");try{await action("share-requirement",{id,version,share:!shared,instructions:shared?"":data.get("instructions")});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Partage impossible.");}finally{setPending(false);}}}><h3>{shared?"Demandée à l’acquéreur":"Demander cette pièce à l’acquéreur"}</h3>{shared?<p className="small muted">Cette demande est visible dans son accompagnement financier.{instructions&&` ${instructions}`}</p>:<label>Consigne pour l’acquéreur<textarea name="instructions" rows={2} maxLength={1500} disabled={locked}/></label>}{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button secondary compact" disabled={pending||(!shared&&locked)}>{pending?"Enregistrement…":shared?"Retirer la demande de son espace":"Publier la demande de pièce"}</button>{!shared&&locked&&<p className="small muted">Le dossier doit être en préparation pour demander une pièce.</p>}</form>;
}
