"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { incidentCategories,incidentUrgencies,incidentChannels,incidentStates,incidentTransitions,progressLabels,type IncidentProgress,type IncidentState } from "@/lib/incident-model";
async function post(action:string,data:unknown){const res=await fetch(`/api/finance/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw new Error(result.error??"Enregistrement impossible.");return result;}
function Options({values}:{values:Record<string,string>}){return Object.entries(values).map(([value,label])=><option key={value} value={value}>{label}</option>);}
type Person={id:string;name:string};
export function IncidentCreateForm({cases,owners,people,userId}:{cases:{id:string;reference:string}[];owners:Person[];people:Person[];userId:string}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setPending(true);setError("");try{const result=await post("incident-create",data);router.push(result.canRead?`/finance/incidents/${result.id}`:`/finance/incidents?recorded=${encodeURIComponent(result.reference)}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid"><label className="wide">Objet du signalement<input name="title" required minLength={5} maxLength={160}/></label><label>Dossier concerné<select name="caseId" defaultValue=""><option value="">Sans dossier rattaché</option>{cases.map(c=><option key={c.id} value={c.id}>{c.reference}</option>)}</select></label><label>Canal de réception<select name="channel" defaultValue="PHONE"><Options values={incidentChannels}/></select></label><label>Auteur du signalement<input name="reporter" required minLength={2} maxLength={160}/></label><label>Contact de retour<input name="contact" maxLength={300}/></label><label>Catégorie<select name="category" defaultValue="OTHER"><Options values={incidentCategories}/></select></label><label>Urgence<select name="urgency" defaultValue="ORDINARY"><Options values={incidentUrgencies}/></select></label><label className="wide">Commande, financement ou projet<input name="project" maxLength={500}/></label><label className="wide">Description factuelle<textarea name="description" required minLength={10} maxLength={5000}/></label><label className="wide">Références des preuves<textarea name="evidence" maxLength={2000}/></label><label>Montant concerné<input name="amount" inputMode="decimal" maxLength={15}/></label><label>Devise<select name="currency" defaultValue="USD"><option>USD</option><option>CDF</option><option>EUR</option></select></label><label className="wide">Mesure immédiate et auteur<textarea name="immediateMeasure" maxLength={2000}/></label><label>Responsable<select name="ownerId" required defaultValue={userId}>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Collaborateur mis en cause<select name="implicatedUserId" defaultValue=""><option value="">Aucun identifié</option>{people.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le signalement"}</button></form>;
}
export function IncidentProgressForm({id,version,status,ownerId,owners,progress}:{id:string;version:number;status:IncidentState;ownerId:string;owners:Person[];progress:IncidentProgress}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));const {ownerId,status,reason,...progress}=raw;setPending(true);setError("");try{await post("incident-update",{id,version,ownerId,status,reason,progress});router.push("/finance/incidents?updated=1");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid"><label>État<select name="status" defaultValue={status==="CLOSED"?"CONTESTED":status}>{(status==="CLOSED"?incidentTransitions[status]:[status,...incidentTransitions[status]]).map(s=><option key={s} value={s}>{incidentStates[s]}</option>)}</select></label><label>Responsable<select name="ownerId" defaultValue={ownerId}>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></div><div className="form-stack">{Object.entries(progressLabels).map(([key,label])=><label key={key}>{label}{key.endsWith("On")?<input type="date" name={key} defaultValue={progress[key as keyof IncidentProgress]}/>:<textarea name={key} rows={2} maxLength={key==="externalContact"?300:["findings","correction","clientResponse"].includes(key)?4000:2000} defaultValue={progress[key as keyof IncidentProgress]}/>}</label>)}<label>Motif de cette mise à jour<textarea name="reason" required minLength={10} maxLength={2000}/></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le suivi"}</button></form>;
}
