"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { currencies } from "@/lib/finance-model";
import { offerFields,rateMethods,type InstitutionInput,type OfferInput } from "@/lib/institution-model";
async function post(action:string,data:unknown){const r=await fetch(`/api/finance/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error??"Enregistrement impossible.");return result;}
const institutionFields={name:"Entité exacte",branch:"Agence",contactName:"Interlocuteur",contactRole:"Fonction",email:"E-mail",phone:"Téléphone",address:"Adresse",notes:"Notes internes"};
export function InstitutionForm({initial,id,version}:{initial?:InstitutionInput;id?:string;version?:number}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));try{const result=await post("institution",{id,version,data});router.push(`/finance/institutions/${result.id}?saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid">{Object.entries(institutionFields).map(([key,label])=><label key={key} className={key==="name"||key==="notes"?"wide":""}>{label}{key==="notes"?<textarea name={key} defaultValue={initial?.notes??""} rows={3} maxLength={2000}/>:<input name={key} defaultValue={initial?.[key as keyof InstitutionInput]??""} type={key==="email"?"email":key==="phone"?"tel":"text"} required={key==="name"} maxLength={key==="address"?500:key==="phone"?40:key==="contactRole"?120:160}/>}</label>)}</div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>Enregistrer</button></form>;
}
const emptyOffer:OfferInput={product:"",amount:"",currency:"USD",durationMonths:"",responseDate:"",validUntil:"",author:"",writtenReference:"",documentId:"",rateMethod:"UNKNOWN",eligibility:"",security:"",pricing:"",schedule:"",disbursement:"",defaultTerms:"",requiredDocuments:"",confirmations:"",complaints:"",kipcityTerms:"",commission:"",support:"",internalNotes:""};
export function OfferForm({caseId,institutions,documents,initial=emptyOffer,id,version,institutionId}:{caseId:string;institutions:{id:string;name:string;branch:string}[];documents:{id:string;name:string}[];initial?:OfferInput;id?:string;version?:number;institutionId?:string}){
 const router=useRouter();const[pending,setPending]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setError("");const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));const selected=institutionId??String(values.institutionId);delete values.institutionId;try{await post("offer",{id,version,caseId,institutionId:selected,data:values});if(!id)form.reset();router.push(`/finance/${caseId}?tab=offres&saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid"><label className="wide">Institution<select name="institutionId" required defaultValue={institutionId??""} disabled={!!id}><option value="">Choisir une institution</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}{i.branch?` · ${i.branch}`:""}</option>)}</select></label><label className="wide">Produit ou objet<input name="product" defaultValue={initial.product} required minLength={2} maxLength={160}/></label><label>Montant proposé<input name="amount" defaultValue={initial.amount} inputMode="decimal" maxLength={15}/></label><label>Devise<select name="currency" defaultValue={initial.currency}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label>Durée (mois)<input name="durationMonths" type="number" min={1} max={9999} step={1} defaultValue={initial.durationMonths}/></label><label>Méthode de taux<select name="rateMethod" defaultValue={initial.rateMethod}>{Object.entries(rateMethods).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Date de réponse<input name="responseDate" type="date" defaultValue={initial.responseDate}/></label><label>Valable jusqu’au<input name="validUntil" type="date" defaultValue={initial.validUntil}/></label><label>Auteur de la réponse<input name="author" defaultValue={initial.author} maxLength={160}/></label><label>Référence écrite<input name="writtenReference" defaultValue={initial.writtenReference} maxLength={200}/></label><label className="wide">Pièce justificative<select name="documentId" defaultValue={initial.documentId}><option value="">Sans pièce jointe</option>{documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><details className="offer-details" open><summary>Conditions de l’offre</summary><div className="form-stack">{Object.entries(offerFields).map(([key,label])=><label key={key}>{label}<textarea name={key} defaultValue={initial[key as keyof typeof offerFields]} rows={2} maxLength={key==="internalNotes"?4000:2000}/></label>)}</div></details></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer l’offre"}</button></form>;
}
