"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {legalTemplates} from "@/lib/legal-templates";
import type {LegalData} from "@/lib/legal";
export function LegalForm({caseId,id,code,version,title,initial,proofs,readOnly}:{caseId:string;id?:string;code:string;version:number;title:string;initial?:LegalData;proofs:{id:string;label:string}[];readOnly:boolean}){
 const router=useRouter(),[pending,setPending]=useState(false),[error,setError]=useState("");const template=legalTemplates[code];
 return <form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);setError("");try{const values:Record<string,string>={},checks:LegalData["checks"]={};for(const section of template.sections){for(const field of section.fields)values[field.key]=String(f.get(field.key)??"");for(const c of section.checks)checks[c.key]={state:String(f.get(c.key)) as "M"|"V"|"NA",reason:String(f.get(`${c.key}-reason`)??""),proofId:String(f.get(`${c.key}-proof`)??"")};}const r=await fetch("/api/legal/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({caseId,id,code,version,title:f.get("title"),reason:f.get("reason"),data:{values,checks,proofIds:f.getAll("proofIds")}})});const d=await r.json();if(!r.ok)throw new Error(d.error);router.push(`/juridique/${caseId}/${d.id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}}><fieldset disabled={pending||readOnly}><label>Objet de cette fiche<input name="title" defaultValue={title} required minLength={3} maxLength={160}/></label>{template.sections.map((section,index)=><section className="panel" key={section.title}><h2>{index+1}. {section.title}</h2><div className="form-grid">{section.fields.map(field=><label key={field.key}>{field.label}<textarea name={field.key} defaultValue={initial?.values[field.key]??""} rows={3} maxLength={6000}/></label>)}</div><h3>Contrôles documentés</h3>{section.checks.map(c=><div className="review-card" key={c.key}><p>{c.label}</p><div className="form-grid"><label>Résultat<select name={c.key} defaultValue={initial?.checks[c.key]?.state??"M"}><option value="M">À examiner / manquant</option><option value="V">Vérifié sur preuve</option><option value="NA">Non applicable, à justifier</option></select></label><label>Pièce examinée<select name={`${c.key}-proof`} defaultValue={initial?.checks[c.key]?.proofId??""}><option value="">Choisir</option>{proofs.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div><label>Constat ou motif<textarea name={`${c.key}-reason`} defaultValue={initial?.checks[c.key]?.reason??""} maxLength={2000} rows={2}/></label></div>)}</section>)}<section className="panel"><h2>Pièces de référence</h2>{proofs.map(p=><label className="check-label" key={p.id}><input name="proofIds" type="checkbox" value={p.id} defaultChecked={initial?.proofIds.includes(p.id)}/>{p.label}</label>)}{!proofs.length&&<p>Aucune pièce contrôlée disponible. Le référent Finance doit compléter les pièces du dossier.</p>}{!readOnly&&<label>Motif de l’enregistrement<textarea name="reason" required minLength={10} maxLength={1000}/></label>}</section></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}{!readOnly&&<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer la fiche"}</button>}</form>;
}
export function LegalDecision({id,version,submit,choices,reopen=false}:{id:string;version:number;submit:boolean;reopen?:boolean;choices:{id:string;name:string}[]}){const router=useRouter(),[pending,setPending]=useState(false),[error,setError]=useState("");return <form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);setError("");try{const r=await fetch("/api/legal/decide",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,version,action:reopen?"REOPEN":submit?"SUBMIT":f.get("action"),part:submit?Number(f.get("part")):undefined,reviewerId:submit?f.get("reviewerId"):undefined,reason:f.get("reason")})});const d=await r.json();if(!r.ok)throw new Error(d.error);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Décision impossible.");}finally{setPending(false);}}}><fieldset disabled={pending}>{submit?<><label>Partie à examiner<select name="part"><option value="1">Partie 1</option><option value="2">Partie 2</option></select></label><label>Intervenant du Cabinet chargé du visa<select name="reviewerId" required defaultValue=""><option value="">Choisir</option>{choices.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>:reopen?<p>Les visas précédents restent dans l’historique. Toute correction nécessite un nouveau visa.</p>:<label>Décision<select name="action"><option value="RETURN">Demander des corrections</option><option value="VISA">Enregistrer le visa du Cabinet</option></select></label>}<label>Motif<textarea name="reason" required minLength={10} maxLength={2000}/></label></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{reopen?"Reprendre la fiche":submit?"Soumettre au visa":"Enregistrer la décision"}</button></form>;}
