import {effectiveLoanFacts,type LoanFact,type LoanData} from "@/lib/loan-model";
import {minorUnits,money} from "@/lib/finance-model";
export function LoanDetails({data:d,currency}:{data:LoanData;currency:string}){
 return <><dl><dt>Référence</dt><dd>{d.reference}</dd><dt>Version du document du prêteur</dt><dd>{d.documentVersion}</dd><dt>Date du fait / réception</dt><dd>{d.eventDate} / {d.receivedDate}</dd><dt>Source</dt><dd>{d.source}</dd>{"amount" in d&&d.amount&&<><dt>Montant</dt><dd>{money(minorUnits(d.amount),currency)}</dd></>}{d.kind==="DECISION"&&<><dt>Décision du prêteur</dt><dd>{{AGREED:"Accord",CONDITIONAL:"Accord sous conditions",REFUSED:"Refus"}[d.outcome]}</dd></>}{d.kind==="CONTRACT"&&<><dt>Offre acceptée</dt><dd>{d.offerReference}</dd><dt>Signataires</dt><dd>{d.parties}</dd></>}{"valueDate" in d&&<><dt>Date de valeur</dt><dd>{d.valueDate}</dd></>}{d.kind==="DISBURSEMENT"&&<><dt>Bénéficiaire effectif</dt><dd>{d.beneficiary} · {{CLIENT:"Client",SUPPLIER:"Fournisseur",PLATFORM:"Plate-Forme"}[d.beneficiaryType]}</dd></>}{d.kind==="PAYMENT"&&<><dt>Payeur</dt><dd>{d.payer}</dd><dt>Échéance concernée</dt><dd>{d.installmentReference}</dd></>}{"conditions" in d&&<><dt>Conditions et formalités</dt><dd style={{whiteSpace:"pre-wrap"}}>{d.conditions}</dd></>}<dt>Observations</dt><dd style={{whiteSpace:"pre-wrap"}}>{d.reason}</dd></dl>{d.kind==="SCHEDULE"&&<><p>Date d’effet : {d.effectiveDate}</p><div className="table-scroll"><table><thead><tr><th>Référence</th><th>Date</th><th>Montant</th></tr></thead><tbody>{d.rows.map(r=><tr key={r.reference}><td>{r.reference}</td><td>{r.date}</td><td>{money(minorUnits(r.amount),currency)}</td></tr>)}</tbody></table></div></>}</>;
}
export function LoanSummary({events,currency}:{events:LoanFact[];currency:string}){
 const facts=effectiveLoanFacts(events),contract=facts.find(e=>e.data.kind==="CONTRACT")?.data,decision=facts.find(e=>e.data.kind==="DECISION")?.data,schedule=facts.find(e=>e.data.kind==="SCHEDULE")?.data,closure=facts.find(e=>e.data.kind==="CLOSURE")?.data;
 const disbursed=facts.reduce((s,e)=>s+(e.data.kind==="DISBURSEMENT"?minorUnits(e.data.amount):0n),0n),paid=facts.reduce((s,e)=>s+(e.data.kind==="PAYMENT"?minorUnits(e.data.amount):0n),0n);
 const sources=facts.map(f=>f.data.eventDate).sort(),today=new Date().toISOString().slice(0,10);
 return <><p className="status">{closure?"Clôture du prêt confirmée":contract?"Contrat signé documenté":decision?.kind==="DECISION"?{AGREED:"Accord documenté",CONDITIONAL:"Accord sous conditions",REFUSED:"Refus documenté"}[decision.outcome]:"Décision à documenter"}</p><div className="form-grid"><div><p className="muted small">Montant signé</p><strong>{contract?.kind==="CONTRACT"?money(minorUnits(contract.amount),currency):"À documenter"}</strong></div><div><p className="muted small">Décaissements contrôlés</p><strong>{money(disbursed,currency)}</strong></div><div><p className="muted small">Remboursements constatés</p><strong>{money(paid,currency)}</strong></div></div><p className="muted small">Dernier fait contrôlé : {sources.at(-1)??"aucun"}. {closure?"Garanties et recours : clôtures distinctes à examiner par le Cabinet.":"Les totaux reflètent uniquement les justificatifs contrôlés."}</p>
 {schedule?.kind==="SCHEDULE"&&<details open><summary>Échéancier en vigueur depuis le {schedule.effectiveDate}</summary><div className="table-scroll"><table><thead><tr><th>Échéance</th><th>Date</th><th>Prévu</th><th>Constaté</th><th>Suivi</th></tr></thead><tbody>{[...schedule.rows].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>{const observed=facts.reduce((s,e)=>s+(e.data.kind==="PAYMENT"&&e.data.installmentReference===r.reference?minorUnits(e.data.amount):0n),0n);return <tr key={r.reference}><td>{r.reference}</td><td>{r.date}</td><td>{money(minorUnits(r.amount),currency)}</td><td>{money(observed,currency)}</td><td>{observed>=minorUnits(r.amount)?"Montant documenté":r.date<=today?"Situation à actualiser":"À venir"}</td></tr>;})}</tbody></table></div></details>}</>;
}
