"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {loanKinds,loanDataSchema,type LoanData} from "@/lib/loan-model";
async function send(url:string,body:FormData|object){const r=await fetch(url,body instanceof FormData?{method:"POST",body}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error||"L’enregistrement a échoué.");}
function useSubmit(){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");return {busy,error,run:async(work:()=>Promise<void>)=>{setBusy(true);setError("");try{await work();router.refresh();}catch(e){setError(e instanceof Error?e.message:"L’enregistrement a échoué.");}finally{setBusy(false);}}};}
function Feedback({error}:{error:string}){return error?<p className="feedback error" role="alert">{error}</p>:null;}
export function LoanCreate({caseId,institutions}:{caseId:string;institutions:{id:string;name:string}[]}){
 const s=useSubmit(),[saved,setSaved]=useState(false);
 return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaved(false);void s.run(async()=>{await send("/api/finance/prets",{caseId,institutionId:f.get("institution"),reference:f.get("reference"),currency:f.get("currency")});setSaved(true);});}}><div className="form-grid"><label>Institution prêteuse<select name="institution" required><option value="">Choisir</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Référence du dossier chez le prêteur<input name="reference" minLength={2} maxLength={160} required/></label><label>Devise<select name="currency"><option>USD</option><option>CDF</option><option>EUR</option></select></label></div><Feedback error={s.error}/>{saved&&<p role="status">Suivi créé.</p>}<button className="button" disabled={s.busy||!institutions.length}>{s.busy?"Enregistrement…":"Créer le suivi"}</button></form>;
}
export function LoanEventForm({loanId,version,corrections}:{loanId:string;version:number;corrections:{id:string;data:LoanData}[]}){
 const s=useSubmit(),[kind,setKind]=useState<LoanData["kind"]>("DECISION"),[replacesId,setReplaces]=useState(""),[outcome,setOutcome]=useState("AGREED"),[rows,setRows]=useState([{reference:"",date:"",amount:""}]),[saved,setSaved]=useState(false);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);void s.run(async()=>{
  const get=(key:string)=>String(f.get(key)??"");
  const common={kind,reference:get("reference"),documentVersion:get("documentVersion"),eventDate:get("eventDate"),receivedDate:get("receivedDate"),source:get("source"),reason:get("reason")};
  const details=kind==="DECISION"?{outcome,amount:outcome==="REFUSED"?"":get("amount"),conditions:get("conditions")}:kind==="CONTRACT"?{amount:get("amount"),offerReference:get("offerReference"),parties:get("parties"),conditions:get("conditions")}:kind==="SCHEDULE"?{effectiveDate:get("effectiveDate"),rows}:kind==="DISBURSEMENT"?{amount:get("amount"),valueDate:get("valueDate"),beneficiaryType:get("beneficiaryType"),beneficiary:get("beneficiary"),conditions:get("conditions")}:kind==="PAYMENT"?{amount:get("amount"),valueDate:get("valueDate"),installmentReference:get("installmentReference"),payer:get("payer")}: {conditions:get("conditions")};
  const parsed=loanDataSchema.safeParse({...common,...details});if(!parsed.success)throw new Error(parsed.error.issues[0].message);
  const body=new FormData();body.set("input",JSON.stringify({loanId,version,replacesId:replacesId||undefined,data:parsed.data}));body.set("file",f.get("file") as File);await send("/api/finance/prets/faits",body);form.reset();setSaved(true);
 });};
 if(saved)return <p className="feedback success" role="status">Fait enregistré. Le contrôleur affecté peut examiner le justificatif.</p>;
 return <form className="form-stack" onSubmit={submit}><div className="form-grid"><label>Fait à enregistrer<select value={kind} onChange={e=>{setKind(e.target.value as LoanData["kind"]);setReplaces("");}}>{Object.entries(loanKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Nouvelle saisie ou correction<select value={replacesId} onChange={e=>setReplaces(e.target.value)}><option value="">Nouvelle saisie</option>{corrections.filter(c=>c.data.kind===kind).map(c=><option key={c.id} value={c.id}>Corriger {c.data.reference} · {c.data.eventDate}</option>)}</select></label><label>Référence du document ou de l’opération<input name="reference" required maxLength={160}/></label><label>Version indiquée par le prêteur<input name="documentVersion" required maxLength={80} placeholder="Version, avenant ou édition datée"/></label><label>Date du fait<input name="eventDate" type="date" required/></label><label>Date de réception<input name="receivedDate" type="date" required/></label><label>Émetteur et origine du justificatif<input name="source" required maxLength={500}/></label>
 {kind==="DECISION"&&<label>Décision<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="AGREED">Accord</option><option value="CONDITIONAL">Accord sous conditions</option><option value="REFUSED">Refus</option></select></label>}
 {(["CONTRACT","DISBURSEMENT","PAYMENT"].includes(kind)||kind==="DECISION"&&outcome!=="REFUSED")&&<label>Montant<input name="amount" required inputMode="decimal"/></label>}
 {kind==="CONTRACT"&&<><label>Référence exacte de l’offre acceptée<input name="offerReference" required maxLength={160}/></label><label>Parties signataires et qualité<input name="parties" required maxLength={1000}/></label></>}
 {(kind==="DISBURSEMENT"||kind==="PAYMENT")&&<label>Date de valeur bancaire<input name="valueDate" type="date" required/></label>}
 {kind==="DISBURSEMENT"&&<><label>Destination<select name="beneficiaryType"><option value="CLIENT">Client</option><option value="SUPPLIER">Fournisseur</option><option value="PLATFORM">Plate-Forme</option></select></label><label>Bénéficiaire effectif<input name="beneficiary" required maxLength={500}/></label></>}
 {kind==="PAYMENT"&&<><label>Référence de l’échéance<input name="installmentReference" required maxLength={80}/></label><label>Payeur indiqué par le prêteur<input name="payer" required maxLength={500}/></label></>}
 {kind==="SCHEDULE"&&<label>Date d’effet de l’échéancier<input name="effectiveDate" type="date" required/></label>}</div>
 {kind==="SCHEDULE"&&<fieldset><legend>Échéances convenues avec le prêteur</legend>{rows.map((r,i)=><div className="form-grid" key={i}>{(["reference","date","amount"] as const).map(key=><label key={key}>{key==="reference"?"Référence":key==="date"?"Échéance":"Montant"}<input aria-label={`${key==="reference"?"Référence":key==="date"?"Date":"Montant"} de l’échéance ${i+1}`} type={key==="date"?"date":"text"} value={r[key]} required onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,[key]:e.target.value}:r))}/></label>)}<button type="button" className="button secondary" disabled={rows.length===1} onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Retirer</button></div>)}<button type="button" className="button secondary" disabled={rows.length>=600} onClick={()=>setRows([...rows,{reference:"",date:"",amount:""}])}>Ajouter une échéance</button></fieldset>}
 {["DECISION","CONTRACT","DISBURSEMENT","CLOSURE"].includes(kind)&&<label>{kind==="CLOSURE"?"Décompte final et confirmation du prêteur":kind==="DISBURSEMENT"?"Conditions de versement et contrôle des formalités":"Conditions, réserves et formalités"}<textarea name="conditions" required maxLength={4000}/></label>}
 <label>{replacesId?"Motif de correction":"Observations de saisie"}<textarea name="reason" required maxLength={2000}/></label><label>Justificatif du prêteur · PDF, JPEG ou PNG · 8 Mo maximum<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label>{kind==="CLOSURE"&&<p>Cette clôture concerne uniquement le prêt. Les garanties et recours restent suivis par le Cabinet.</p>}<Feedback error={s.error}/><button className="button" disabled={s.busy}>{s.busy?"Dépôt…":"Soumettre au contrôle"}</button></form>;
}
export function LoanReview({id,version}:{id:string;version:number}){const s=useSubmit();return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void s.run(()=>send("/api/finance/prets/controle",{id,version,decision:f.get("decision"),sourceChecked:f.get("checked")==="on",reason:f.get("reason")}));}}><label>Résultat du contrôle<select name="decision"><option value="ACCEPTED">Fait confirmé par le justificatif</option><option value="REJECTED">Écart à corriger</option></select></label><label className="check-label"><input type="checkbox" name="checked" required/>J’ai examiné l’émetteur, la référence, les montants, les parties, les dates et les doublons.</label><label>Conclusion motivée<textarea name="reason" required minLength={10} maxLength={2000}/></label><Feedback error={s.error}/><button className="button" disabled={s.busy}>{s.busy?"Enregistrement…":"Enregistrer le contrôle"}</button></form>;}
