"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { memberFinanceStages,type MemberUpdate } from "@/lib/member-finance-model";
async function send(data:unknown){const res=await fetch("/api/finance/member-update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw new Error(result.error??"Enregistrement impossible.");}
export function MemberFinanceForm({caseId,version,initial}:{caseId:string;version:number;initial:MemberUpdate}){
 const router=useRouter();const[documents,setDocuments]=useState(initial.documents);const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data={...Object.fromEntries(new FormData(e.currentTarget)),documents};setPending(true);setError("");try{await send({action:"save",caseId,version,data});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid"><label className="wide">Titre pour l’acquéreur<input name="title" required minLength={3} maxLength={160} defaultValue={initial.title}/></label><label>Avancement<select name="stage" defaultValue={initial.stage}>{Object.entries(memberFinanceStages).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="wide">Message à l’acquéreur<textarea name="message" required minLength={10} maxLength={3000} rows={4} defaultValue={initial.message}/></label></div><h3>Éléments à fournir</h3>{documents.map((d,i)=><div className="review-card" key={i}><label>Élément {i+1}<input value={d.label} required minLength={2} maxLength={160} onChange={e=>setDocuments(documents.map((r,j)=>j===i?{...r,label:e.target.value}:r))}/></label><label>Date souhaitée<input type="date" value={d.dueOn} onChange={e=>setDocuments(documents.map((r,j)=>j===i?{...r,dueOn:e.target.value}:r))}/></label><button className="button secondary compact" type="button" onClick={()=>setDocuments(documents.filter((_,j)=>j!==i))}>Retirer l’élément {i+1}</button></div>)}{documents.length<20&&<button type="button" className="button secondary compact" onClick={()=>setDocuments([...documents,{label:"",dueOn:""}])}>Ajouter un élément</button>}<h3>Rendez-vous</h3><div className="form-grid"><label>Date<input type="date" name="appointmentDate" defaultValue={initial.appointmentDate}/></label><label>Heure de Kinshasa<input type="time" name="appointmentTime" defaultValue={initial.appointmentTime}/></label><label className="wide">Lieu ou mode de rendez-vous<input name="appointmentPlace" maxLength={300} defaultValue={initial.appointmentPlace}/></label><label className="wide">Contact à afficher<input name="contact" maxLength={300} defaultValue={initial.contact}/></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le brouillon"}</button></form>;
}
export function MemberPublicationActions({caseId,version,visible,canPublish}:{caseId:string;version:number;visible:boolean;canPublish:boolean}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function act(action:"publish"|"withdraw"){setPending(true);setError("");try{await send({action,caseId,version});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Action impossible.");}finally{setPending(false);}}
 return <div className="form-stack"><div className="actions"><button className="button" disabled={pending||!canPublish} onClick={()=>act("publish")}>Publier cet aperçu</button>{visible&&<button className="button secondary" disabled={pending} onClick={()=>act("withdraw")}>Retirer de MyKipCity</button>}</div>{error&&<p role="alert" className="feedback error">{error}</p>}</div>;
}
