"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { documentCategories } from "@/lib/member-document-model";
async function send(url:string,data:unknown){const multipart=data instanceof FormData;const res=await fetch(url,{method:"POST",...(multipart?{}:{headers:{"Content-Type":"application/json"}}),body:multipart?data:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw new Error(result.error??"Opération impossible.");}
export function MemberDocumentCreate({fileId,parcels}:{fileId:string;parcels:string[]}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setPending(true);setError("");try{await send("/api/member-documents",{fileId,title:data.get("title"),category:data.get("category"),direction:data.get("direction"),instructions:data.get("instructions"),parcelReferences:data.getAll("parcelReferences")});form.reset();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset className="form-stack" disabled={pending}><label>Action<select name="direction"><option value="REQUESTED">Demander une pièce au client</option><option value="RECEIVED">Remettre un document au client</option></select></label><label>Intitulé<input name="title" required minLength={3} maxLength={160}/></label><label>Type<select name="category">{Object.entries(documentCategories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><fieldset className="form-stack"><legend>Parcelles concernées — facultatif</legend>{parcels.map(ref=><label className="check-label" key={ref}><input type="checkbox" name="parcelReferences" value={ref}/>{ref}</label>)}</fieldset><label>Consignes ou message<textarea name="instructions" maxLength={2000} rows={3}/></label></fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}<button className="button" disabled={pending}>Enregistrer</button></form>;
}
export function MemberDocumentUpload({id,version}:{id:string;version:number}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);data.set("documentId",id);data.set("version",String(version));setPending(true);setError("");try{await send("/api/member-documents/upload",data);form.reset();router.refresh();}catch(e){setError(e instanceof Error?e.message:"Dépôt impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><label>{version?"Déposer une nouvelle version":"Choisir le document"}<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg" required disabled={pending}/><span className="hint">PDF, JPEG ou PNG · 8 Mo maximum</span></label>{error&&<p className="feedback error" role="alert">{error}</p>}<button disabled={pending} className="button compact">{pending?"Dépôt…":"Déposer le fichier"}</button></form>;
}
export function MemberDocumentReview({id,version}:{id:string;version:number}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setPending(true);setError("");try{await send("/api/member-documents/review",{...data,documentId:id,version});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Contrôle impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset className="form-stack" disabled={pending}><label>Résultat du contrôle<select name="decision"><option value="ACCEPTED">Accepter la pièce</option><option value="NEEDS_INFO">Demander une correction</option></select></label><label>Motif communiqué au client<textarea name="reason" required minLength={5} maxLength={2000} rows={2}/></label></fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}<button disabled={pending} className="button compact">Enregistrer le contrôle</button></form>;
}
export function MemberDocumentClose({id,version,direction}:{id:string;version:number;direction:string}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 return <details className="document-history"><summary>{direction==="REQUESTED"?"Annuler la demande":"Retirer ce document de l’espace client"}</summary><form className="form-stack" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{await send("/api/member-documents/close",{id,version,reason:form.get("reason")});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Modification impossible.");}finally{setPending(false);}}}><label>Motif<textarea name="reason" required minLength={5} maxLength={2000} rows={2}/></label><p className="small muted">Les fichiers et leur historique restent conservés pour l’équipe.</p>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button secondary compact" disabled={pending}>{direction==="REQUESTED"?"Confirmer l’annulation":"Confirmer le retrait"}</button></form></details>;
}
