"use client";
import {useState} from "react";
import {authClient} from "@/lib/auth-client";
import {useRouter} from "next/navigation";
export function MfaSettings({enabled}:{enabled:boolean}){
 const router=useRouter();const[setup,setSetup]=useState<{totpURI:string;backupCodes:string[]}|null>(null),[pending,setPending]=useState(false),[error,setError]=useState("");
 return <div><p>{enabled?"Double authentification activée.":"Ajoutez un code temporaire à votre mot de passe."}</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setPending(true);setError("");try{if(setup){const r=await authClient.twoFactor.verifyTotp({code:String(f.get("code"))});if(r.error)throw new Error("Code incorrect. Réessayez.");setSetup(null);router.refresh();}else if(enabled){const r=await authClient.twoFactor.disable({password:String(f.get("password"))});if(r.error)throw new Error("Désactivation refusée. Vérifiez votre mot de passe.");router.refresh();}else{const r=await authClient.twoFactor.enable({password:String(f.get("password"))});if(r.error||!r.data||r.data.method!=="totp")throw new Error("Activation refusée. Vérifiez votre mot de passe.");setSetup(r.data);}}catch(e){setError(e instanceof Error?e.message:"Opération impossible.");}finally{setPending(false);}}}><fieldset disabled={pending}>{setup?<><label>Clé à saisir dans votre application d’authentification<input readOnly value={new URL(setup.totpURI).searchParams.get("secret")??""}/></label><p>Compte : Kip-City · Code à 6 chiffres, renouvelé toutes les 30 secondes.</p><details open><summary>Codes de secours à conserver</summary><p>Chaque code ne peut être utilisé qu’une fois.</p><pre>{setup.backupCodes.join("\n")}</pre></details><label className="check-label"><input type="checkbox" required/>J’ai conservé mes codes de secours.</label><label>Code de l’application<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required/></label></>:<label>Mot de passe actuel<input name="password" type="password" autoComplete="current-password" required/></label>}</fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{setup?"Confirmer l’activation":enabled?"Désactiver":"Configurer la double authentification"}</button></form></div>;
}
export function VerifyEmail({email,verified}:{email:string;verified:boolean}){const[pending,setPending]=useState(false),[message,setMessage]=useState("");return <div><p>{verified?"Adresse vérifiée":"Adresse à vérifier"}</p>{!verified&&<button className="button secondary" disabled={pending} onClick={async()=>{setPending(true);try{const r=await authClient.sendVerificationEmail({email,callbackURL:"/compte"});setMessage(r.error?"Demande impossible. Réessayez plus tard.":"Un lien de vérification a été demandé.");}catch{setMessage("Demande impossible. Réessayez plus tard.");}finally{setPending(false);}}}>Vérifier mon adresse</button>}{message&&<p role="status">{message}</p>}</div>;}
