"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { currencies, money } from "@/lib/finance-model";
import { arrangements, opportunityStates, costKinds, resourceKinds, opportunityFields, opportunitySchema, emptyOpportunity, summarizeOpportunity, type Opportunity } from "@/lib/opportunity-model";
export type OpportunityProof={id:string;label:string};
export function OpportunityForm({initial=emptyOpportunity,id="snapshot",version=0,documents=[],readOnly=false}:{initial?:Opportunity;id?:string;version?:number;documents?:OpportunityProof[];readOnly?:boolean}){
 const [value,setValue]=useState(initial),[pending,setPending]=useState(false),[error,setError]=useState("");const router=useRouter();
 function patch(data:Partial<Opportunity>){setValue(v=>({...v,...data}));}
 function proof(documentId:string,onChange:(id:string)=>void){const exists=documents.some(d=>d.id===documentId);return <select value={documentId} onChange={e=>onChange(e.target.value)}><option value="">À joindre</option>{documentId&&!exists&&<option value={documentId}>Pièce à actualiser</option>}{documents.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select>;}
 async function submit(e:FormEvent){e.preventDefault();setPending(true);setError("");try{const parsed=opportunitySchema.safeParse(value);if(!parsed.success)throw new Error(parsed.error.issues[0].message);const response=await fetch("/api/finance/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,version,code:"FIN-F07",data:parsed.data})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Enregistrement impossible.");router.push(`/finance/${id}?tab=opportunite&saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 const parsed=opportunitySchema.safeParse(value);
 return <form className="form-stack" onSubmit={submit}><h2>Étude d’opportunité</h2><p className="muted small">Cette étude ne vaut ni financement, ni engagement, ni droit foncier.</p><fieldset disabled={readOnly||pending}>
 <div className="form-grid">{(["project","operator","entity","location"] as const).map(key=><label key={key}>{opportunityFields[key]}<textarea rows={2} maxLength={3000} value={value[key]} onChange={e=>patch({[key]:e.target.value})}/></label>)}<label>Montage envisagé<select value={value.arrangement} onChange={e=>patch({arrangement:e.target.value as Opportunity["arrangement"]})}>{Object.entries(arrangements).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Situation déclarée<select value={value.status} onChange={e=>patch({status:e.target.value as Opportunity["status"]})}>{Object.entries(opportunityStates).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="wide">{opportunityFields.arrangementNotes}<textarea rows={2} maxLength={3000} value={value.arrangementNotes} onChange={e=>patch({arrangementNotes:e.target.value})}/></label></div>
 <h2>Emplois du projet</h2>{value.costs.map((line,i)=>{function change(data:Partial<Opportunity["costs"][number]>){patch({costs:value.costs.map((l,n)=>n===i?{...l,...data}:l)});}return <section className="budget-line" key={i}><div className="form-grid"><label>Poste<select value={line.category} onChange={e=>change({category:e.target.value as typeof line.category})}>{Object.entries(costKinds).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Libellé<input required maxLength={300} value={line.label} onChange={e=>change({label:e.target.value})}/></label><label>Montant<input required inputMode="decimal" maxLength={15} value={line.amount} onChange={e=>change({amount:e.target.value})}/></label><label>Devise<select value={line.currency} onChange={e=>change({currency:e.target.value as typeof line.currency})}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label className="wide">Justificatif{proof(line.documentId,documentId=>change({documentId}))}</label></div>{!readOnly&&<button type="button" className="button secondary compact" onClick={()=>patch({costs:value.costs.filter((_,n)=>n!==i)})}>Retirer ce poste</button>}</section>;})}{!readOnly&&value.costs.length<40&&<button type="button" className="button secondary compact" onClick={()=>patch({costs:[...value.costs,{category:"STUDIES",label:"",amount:"",currency:"USD",documentId:""}]})}>Ajouter un emploi</button>}
 <h2>Ressources et apports</h2>{value.resources.map((line,i)=>{function change(data:Partial<Opportunity["resources"][number]>){patch({resources:value.resources.map((l,n)=>n===i?{...l,...data}:l)});}return <section className="budget-line" key={i}><div className="form-grid"><label>Origine<select value={line.source} onChange={e=>change({source:e.target.value as typeof line.source})}>{Object.entries(resourceKinds).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Apporteur et apport<input required maxLength={300} value={line.label} onChange={e=>change({label:e.target.value})}/></label><label>Nature<select value={line.kind} onChange={e=>change({kind:e.target.value as typeof line.kind})}><option value="CASH">Argent</option><option value="IN_KIND">Actif évalué</option></select></label><label>État<select value={line.status} onChange={e=>change({status:e.target.value as typeof line.status})}><option value="PROPOSED">Envisagé</option><option value="DOCUMENTED">Documenté</option></select></label><label>Montant ou valeur<input required inputMode="decimal" maxLength={15} value={line.amount} onChange={e=>change({amount:e.target.value})}/></label><label>Devise<select value={line.currency} onChange={e=>change({currency:e.target.value as typeof line.currency})}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label className="wide">Statut, conditions et contrepartie<textarea rows={2} maxLength={3000} value={line.counterpart} onChange={e=>change({counterpart:e.target.value})}/></label><label className="wide">Justificatif{proof(line.documentId,documentId=>change({documentId}))}</label></div>{!readOnly&&<button type="button" className="button secondary compact" onClick={()=>patch({resources:value.resources.filter((_,n)=>n!==i)})}>Retirer cet apport</button>}</section>;})}{!readOnly&&value.resources.length<40&&<button type="button" className="button secondary compact" onClick={()=>patch({resources:[...value.resources,{source:"OPERATOR",kind:"CASH",status:"PROPOSED",label:"",amount:"",currency:"USD",documentId:"",counterpart:""}]})}>Ajouter un apport</button>}
 <h2>Conditions et gouvernance</h2>{(["revenues","assets","remuneration","reporting","interests","visas"] as const).map(key=><label key={key}>{opportunityFields[key]}<textarea rows={3} maxLength={3000} value={value[key]} onChange={e=>patch({[key]:e.target.value})}/></label>)}
 <h2>Avis et décisions</h2><p className="muted small">Les pièces sont déposées et contrôlées dans l’onglet Pièces.</p>{([["financeDocumentId","Avis Finance"],["legalDocumentId","Avis du Cabinet"],["decisionDocumentId","Décision compétente / offre ou accord externe"]] as const).map(([key,label])=><label key={key}>{label}{proof(value[key],documentId=>patch({[key]:documentId}))}</label>)}<label><input type="checkbox" checked={value.valuesChecked} onChange={e=>patch({valuesChecked:e.target.checked})}/> Apports et valeurs contrôlables, sans doublon</label><label><input type="checkbox" checked={value.interestsChecked} onChange={e=>patch({interestsChecked:e.target.checked})}/> Intérêts liés et décisions réservées identifiés</label>
 </fieldset>{parsed.success&&<section className="panel"><h2>Équilibre prévisionnel</h2>{summarizeOpportunity(parsed.data).map(s=><div className="budget-summary" key={s.currency}><h3>{s.currency}</h3><dl><dt>Emplois renseignés</dt><dd>{money(s.cost,s.currency)}</dd><dt>Apports en argent envisagés</dt><dd>{money(s.cash,s.currency)}</dd><dt>Actifs évalués envisagés</dt><dd>{money(s.inKind,s.currency)}</dd><dt>Besoin non couvert</dt><dd>{s.complete?money(s.need>0n?s.need:0n,s.currency):"Postes à compléter"}</dd>{s.complete&&s.need<0n&&<><dt>Excédent prévisionnel</dt><dd>{money(-s.need,s.currency)}</dd></>}</dl></div>)}<p className="muted small">Renseignez les quatre postes de coûts, même à zéro. Les apports envisagés ne sont pas des fonds disponibles. Aucun change entre devises.</p></section>}{error&&<p className="feedback error" role="alert">{error}</p>}{!readOnly&&<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer l’étude"}</button>}</form>;
}
