"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {originalKinds,originalData,type OriginalData} from "@/lib/original-model";
import {inventoryLabels,movementLabels} from "@/lib/original-labels";
async function send(url:string,body:FormData|object){const r=await fetch(url,body instanceof FormData?{method:"POST",body}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw new Error(result.error||"L’enregistrement a échoué.");return result as {id?:string};}
export function OriginalForm({caseId,id,reference,version=0,reviewers,kinds,last,initial,correction=false}:{caseId:string;id?:string;reference?:string;version?:number;reviewers:{id:string;name:string}[];kinds:(keyof typeof originalKinds)[];last?:{id:string;data:OriginalData};initial?:OriginalData;correction?:boolean}){
 const router=useRouter(),[kind,setKind]=useState<keyof typeof originalKinds>(correction&&last?last.data.kind:initial?.kind??kinds[0]??"DEPOSIT"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const values=correction?last?.data:initial;
 return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),get=(key:string)=>String(f.get(key)??"");setBusy(true);setError("");void(async()=>{try{
  const inventory=kind==="DEPOSIT"?{...Object.fromEntries(Object.keys(inventoryLabels).map(key=>[key,get(`inventory.${key}`)])),pages:Number(get("inventory.pages")),copyDelivered:f.get("copyDelivered")==="on",authenticityExamined:f.get("authenticityExamined")==="on"}:undefined;
  const parsed=originalData.safeParse({kind,...Object.fromEntries(Object.keys(movementLabels).map(key=>[key,get(key)])),occurredAt:get("occurredAt"),returnDue:get("returnDue"),returnTerms:get("returnTerms"),inventory});if(!parsed.success)throw new Error(parsed.error.issues[0].message);
  const body=new FormData();body.set("input",JSON.stringify({caseId,id,version,reference:reference??get("reference"),reviewerId:get("reviewerId"),replacesId:correction?last?.id:undefined,data:parsed.data}));body.set("file",f.get("file") as File);
  const result=await send("/api/juridique/originaux",body);router.push(`/juridique/originaux/${result.id}`);router.refresh();
 }catch(e){setError(e instanceof Error?e.message:"L’enregistrement a échoué.");}finally{setBusy(false);}})();}}>
 {!id&&<label>Référence d’inventaire unique<input name="reference" required minLength={2} maxLength={100} placeholder="ORI-2026-001"/></label>}
 <div className="form-grid"><label>Événement<select value={kind} disabled={correction||kinds.length===1} onChange={e=>setKind(e.target.value as keyof typeof originalKinds)}>{(correction?[kind]:kinds).map(k=><option key={k} value={k}>{originalKinds[k]}</option>)}</select></label><label>Date et heure du fait · Kinshasa<input name="occurredAt" type="datetime-local" required defaultValue={values?.occurredAt}/></label></div>
 {kind==="DEPOSIT"&&<fieldset><legend>Inventaire contradictoire</legend><div className="form-grid">{Object.entries(inventoryLabels).map(([key,label])=><label key={key}>{label}<input name={`inventory.${key}`} type={key==="pages"?"number":key==="documentDate"?"date":"text"} min={key==="pages"?1:undefined} max={key==="pages"?10000:undefined} required maxLength={2000} defaultValue={values?.inventory?.[key as keyof typeof inventoryLabels]}/></label>)}</div><label className="check-label"><input type="checkbox" name="copyDelivered" required/>Copie complète et reçu remis au remettant.</label><label className="check-label"><input type="checkbox" name="authenticityExamined" required/>Authenticité et portée de la pièce examinées séparément.</label></fieldset>}
 <div className="form-grid">{Object.entries(movementLabels).map(([key,label])=><label key={key}>{label}{["authority","signatories","discrepancies","reason"].includes(key)?<textarea name={key} required maxLength={2000} defaultValue={values?.[key as keyof typeof movementLabels]}/>:<input name={key} required={!["incidentReference","transport"].includes(key)} maxLength={key==="incidentReference"?160:key==="receipt"?300:["place","location"].includes(key)?500:2000} defaultValue={values?.[key as keyof typeof movementLabels]??(["holder","location"].includes(key)?last?.data[key as "holder"|"location"]:undefined)}/>}</label>)}</div>
 {kind==="TEMPORARY_OUT"&&<div className="form-grid"><label>Retour attendu le<input type="date" name="returnDue" defaultValue={values?.returnDue}/></label><label>Ou événement attendu pour le retour<textarea name="returnTerms" maxLength={2000} defaultValue={values?.returnTerms}/></label></div>}
 {kind==="LOSS"||kind==="DAMAGE"?<p className="muted small">Si le signalement FIN-F08 n’existe pas encore, indiquez dans les observations l’action attendue de Finance.</p>:null}
 <label>Reçu signé ou constat justificatif · PDF, JPEG, PNG · 8 Mo maximum<input name="file" type="file" required accept="application/pdf,image/png,image/jpeg"/></label><label>Contrôleur du Cabinet<select name="reviewerId" required><option value="">Choisir un intervenant distinct</option>{reviewers.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>{!reviewers.length&&<p className="feedback">Un second intervenant actif du Cabinet doit être désigné dans l’équipe.</p>}{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={busy||!reviewers.length}>{busy?"Enregistrement…":"Soumettre au contrôle"}</button></form>;
}
export function OriginalDecision({id,version,cancel=false}:{id:string;version:number;cancel?:boolean}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState("");return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError("");void send("/api/juridique/originaux/controle",{id,version,action:cancel?"CANCELLED":f.get("action"),checks:f.get("checks")==="on",reason:f.get("reason")}).then(()=>{router.push("/juridique/originaux");router.refresh();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{!cancel&&<><label>Résultat<select name="action"><option value="ACCEPTED">Constat confirmé</option><option value="REJECTED">Écart à corriger</option></select></label><label className="check-label"><input type="checkbox" name="checks"/>Identités et pouvoirs vérifiés, inventaire comparé, conditions de garde respectées, preuve conservée et personnes concernées informées.</label></>}<label>{cancel?"Motif du retrait":"Conclusion motivée"}<textarea name="reason" minLength={10} maxLength={2000} required/></label>{error&&<p role="alert" className="feedback error">{error}</p>}<button className={cancel?"button secondary":"button"} disabled={busy}>{busy?"Enregistrement…":cancel?"Retirer du contrôle":"Enregistrer le contrôle"}</button></form>;}
