"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { publicationAudiences,type PublicationContent } from "@/lib/publication-model";
async function send(input:unknown){const res=await fetch("/api/publications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const data=await res.json();if(!res.ok)throw new Error(data.error??"Enregistrement impossible.");return data as {id:string};}
export function PublicationForm({id,version=0,initial={title:"",body:"",audience:"MEMBERS",targetReference:""}}:{id?:string;version?:number;initial?:PublicationContent}){
 const router=useRouter();const[audience,setAudience]=useState(initial.audience);const[error,setError]=useState("");const[pending,setPending]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));setPending(true);setError("");try{const data=await send({action:"save",id,version,content:{...fields,audience,targetReference:audience==="MEMBERS"?"":fields.targetReference}});router.push(`/gestion/publications/${data.id}?saved=1`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset className="form-stack" disabled={pending}><label>Titre<input name="title" defaultValue={initial.title} required minLength={3} maxLength={160}/></label><label>Destinataires<select value={audience} onChange={e=>setAudience(e.target.value as PublicationContent["audience"])}>{Object.entries(publicationAudiences).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{audience!=="MEMBERS"&&<label>{audience==="PARCEL"?"Référence de la parcelle":"Référence de l’acquéreur"}<input key={audience} name="targetReference" defaultValue={audience===initial.audience?initial.targetReference:""} required maxLength={100} placeholder={audience==="PARCEL"?"Ex. DEMO-A01":"Ex. ACQ-DEMO-001"}/></label>}<label>Contenu<textarea name="body" defaultValue={initial.body} required minLength={10} maxLength={10000} rows={10}/></label></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Enregistrer le brouillon"}</button></form>;
}
export function PublicationActions({id,version,actions}:{id:string;version:number;actions:{action:string;label:string}[]}){
 const router=useRouter();const[reason,setReason]=useState("");const[publishAt,setPublishAt]=useState("");const[error,setError]=useState("");const[pending,setPending]=useState(false);
 if(!actions.length)return null;
 async function act(action:string){setPending(true);setError("");try{await send({id,version,action,reason,...(action==="publish"&&publishAt?{publishAt:`${publishAt}:00+01:00`}:{})});setReason("");router.replace(`/gestion/publications/${id}`);router.refresh();}catch(e){setError(e instanceof Error?e.message:"Action impossible.");}finally{setPending(false);}}
 return <div className="form-stack">{actions.some(a=>a.action==="publish")&&<label>Date de publication — facultatif<input type="datetime-local" value={publishAt} onChange={e=>setPublishAt(e.target.value)} disabled={pending}/><span className="hint">Heure de Kinshasa. Laissez vide pour publier immédiatement après approbation.</span></label>}<label>Motif ou commentaire<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} rows={2} disabled={pending}/></label><div className="actions">{actions.map(a=><button className="button" key={a.action} onClick={()=>act(a.action)} disabled={pending||reason.trim().length<3}>{a.action==="publish"&&publishAt?"Approuver et programmer":a.label}</button>)}</div>{error&&<p role="alert" className="feedback error">{error}</p>}</div>;
}
