"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import {importHeaders,type ImportKind} from "@/lib/registry-import-model";
async function send(action:string,data:unknown){const r=await fetch(`/api/registry-import/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw new Error(result.error??"Import impossible.");return result;}
export function ImportPreviewForm(){const router=useRouter();const[kind,setKind]=useState<ImportKind>("ACQUIRERS"),[error,setError]=useState(""),[pending,setPending]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{const file=form.get("csv");if(!(file instanceof File)||!file.size||file.size>262144)throw new Error("Choisissez un fichier CSV de 256 Ko maximum.");const result=await send("preview",{kind,filename:file.name.slice(0,160),csv:await file.text()});router.push(`/gestion/imports/${result.id}`);}catch(e){setError(e instanceof Error?e.message:"Analyse impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><label>Registre<select value={kind} onChange={e=>setKind(e.target.value as ImportKind)}><option value="ACQUIRERS">Acquéreurs</option><option value="PARCELS">Parcelles</option></select></label><label>Fichier CSV<input name="csv" type="file" accept=".csv,text/csv" required/></label><p className="muted small">UTF-8 · 500 lignes maximum · 256 Ko. Séparateur virgule ou point-virgule.</p><a className="text-link" download={kind==="ACQUIRERS"?"modele-acquereurs.csv":"modele-parcelles.csv"} href={`data:text/csv;charset=utf-8,${encodeURIComponent("\uFEFF"+importHeaders[kind].join(";")+"\r\n")}`}>Télécharger le modèle CSV</a><p>Colonnes : {importHeaders[kind].join(" · ")}</p>{kind==="PARCELS"&&<p className="muted small">Superficie en m² entiers. Une référence cadastrale individuelle par parcelle.</p>}</fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Analyse…":"Analyser le fichier"}</button></form>;
}
export function ImportConfirmForm({id,warnings,created}:{id:string;warnings:boolean;created:number}){const router=useRouter();const[error,setError]=useState(""),[pending,setPending]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);setError("");try{await send("confirm",{id,confirmed:data.get("confirmed")==="on",warningsAccepted:data.get("warnings")==="on"});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Confirmation impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}>{warnings&&<label className="check-label"><input name="warnings" type="checkbox" required/><span>J’ai vérifié les noms similaires : il s’agit de personnes distinctes.</span></label>}<label className="check-label"><input name="confirmed" type="checkbox" required/><span>J’ai vérifié l’aperçu et confirme la création de {created} fiche{created>1?"s":""}.</span></label></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":"Confirmer l’import"}</button></form>;
}
