import { OpportunityForm } from "./opportunity-form";
import { opportunitySchema } from "@/lib/opportunity-model";
import { requestSchema,budgetSchema,money,minorUnits } from "@/lib/finance-model";
import { offerSchema,offerFields,rateMethods } from "@/lib/institution-model";
import { RequestForm,BudgetForm,BudgetSummary } from "./finance-forms";
export function ReviewSnapshot({snapshot}:{snapshot:unknown}) {
 const value=snapshot as {opportunity?:unknown;request:unknown;budget:unknown;preparer:{name:string};reviewer:{name:string};validator:{name:string};documents:{id:string;label:string;name:string;revision:number;reason:string}[];offers:{id:string;version:number;institution:{name:string};data:unknown}[]};
 const request=requestSchema.parse(value.request),budget=budgetSchema.parse(value.budget);
 return <div className="stack"><p>Affectations lors de la soumission — préparation : {value.preparer.name} · Contrôle : {value.reviewer.name} · Validation : {value.validator.name}</p><details className="panel" open><summary>Demande</summary><RequestForm initial={request} readOnly/></details><details className="panel"><summary>Budget</summary><BudgetSummary budget={budget}/><BudgetForm id="snapshot" version={0} initial={budget} readOnly/></details><>{value.opportunity&&<details className="panel"><summary>Étude d’opportunité</summary><OpportunityForm initial={opportunitySchema.parse(value.opportunity)} readOnly documents={value.documents.map(d=>({id:d.id,label:`${d.label} · ${d.name} · v${d.revision}`}))}/></details>}</><section className="panel"><h2>Pièces examinées</h2>{value.documents.map(d=><article key={d.id} className="review-card"><h3>{d.label}</h3><a className="text-link" href={`/api/finance/documents/${d.id}`}>{d.name} · Version {d.revision} ↓</a><p>{d.reason}</p></article>)}</section><section className="panel"><h2>Offres incluses</h2>{value.offers.map(o=>{const v=offerSchema.parse(o.data);return <details key={o.id} className="review-card"><summary>{o.institution.name} · {v.product} · Version {o.version}</summary><dl className="revision-values">{[["Montant",v.amount?money(minorUnits(v.amount),v.currency):"Non renseigné"],["Durée",v.durationMonths?`${v.durationMonths} mois`:""],["Méthode de taux",rateMethods[v.rateMethod]],["Auteur de la réponse",v.author],["Référence",v.writtenReference],["Date de réponse",v.responseDate],["Valable jusqu’au",v.validUntil],...Object.entries(offerFields).map(([key,label])=>[label,v[key as keyof typeof offerFields]])].map(([label,text])=><div key={label}><dt>{label}</dt><dd>{text||"Non renseigné"}</dd></div>)}</dl>{v.documentId&&<a className="text-link" href={`/api/finance/documents/${v.documentId}`}>Pièce jointe à l’offre ↓</a>}</details>;})}{!value.offers.length&&<p>Aucune offre incluse.</p>}</section></div>;
}
