"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
async function send(action:string, data:unknown) { const res=await fetch(`/api/finance/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw new Error(result.error??"Action impossible."); }
export function SubmitReviewForm({id,version,reviewers,validators}:{id:string;version:number;reviewers:{id:string;name:string}[];validators:{id:string;name:string}[]}) {
 const router=useRouter();const [pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setPending(true);setError("");try{await send("submit-review",{id,version,reviewerId:data.get("reviewerId"),validatorId:data.get("validatorId")});router.refresh();}catch(e){setError(e instanceof Error?e.message:"Action impossible.");}finally{setPending(false);}}
 if(!reviewers.length||!validators.length)return <p>Un contrôleur et un validateur Finance actifs doivent être désignés dans « Équipe et accès ».</p>;
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-grid">{[["reviewerId","Contrôleur",reviewers],["validatorId","Validateur",validators]].map(([name,label,people])=><label key={name as string}>{label as string}<select name={name as string} required defaultValue=""><option value="">Choisir</option>{(people as {id:string;name:string}[]).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>)}</div></fieldset><p className="muted">Le dossier sera verrouillé pendant son examen. Les pièces attendues doivent être contrôlées et le budget renseigné.</p>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>Soumettre au contrôle</button></form>;
}
export function ReviewDecisionForm({id,version,stage}:{id:string;version:number;stage:"control"|"validate"|"withdraw"}){
 const router=useRouter();const[pending,setPending]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{await send("decide-review",{id,version,action:stage==="withdraw"?"WITHDRAW":form.get("action"),reason:form.get("reason"),...(stage==="control"?{checks:{identity:form.get("identity")==="on",budget:form.get("budget")==="on",documents:form.get("documents")==="on"}}:{})});if(form.get("action")==="RETURN")router.push("/finance/controles");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Action impossible.");}finally{setPending(false);}}
 return <form className="form-stack" onSubmit={submit}><fieldset disabled={pending}><div className="form-stack">{stage==="control"&&<>{[["identity","Identité et qualité du demandeur examinées"],["budget","Budget et cohérence des montants examinés"],["documents","Pièces et références examinées"]].map(([name,label])=><label className="check-label" key={name}><input type="checkbox" name={name}/><span>{label}</span></label>)}</>}{stage!=="withdraw"&&<label>Décision<select name="action" defaultValue="" required><option value="">Choisir une décision</option><option value={stage==="control"?"CONTROL":"VALIDATE"}>{stage==="control"?"Contrôle favorable":"Valider en interne"}</option><option value="RETURN">Demander des corrections</option></select></label>}<label>{stage==="withdraw"?"Motif du retrait":"Observations et motif"}<textarea name="reason" required minLength={10} maxLength={2000}/></label></div></fieldset>{error&&<p className="feedback error" role="alert">{error}</p>}<button className="button" disabled={pending}>{pending?"Enregistrement…":stage==="withdraw"?"Retirer du circuit":"Enregistrer la décision"}</button></form>;
}
