import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Logout } from "./forms";
import { NotificationLink } from "./notification-link";
import { ShellNavigation } from "./shell-navigation";
import { MobileNavigation } from "./mobile-navigation";
export function Brand(){return <Link href="/" className="brand"><span className="brand-mark" aria-hidden><i/><i/><i/></span><span>Kip-City<small>ESPACE PRIVÉ</small></span></Link>;}
export function Shell({name,staff=false,finance=false,admin=false,control=false,legal=false,children}:{name:string;staff?:boolean;finance?:boolean;admin?:boolean;control?:boolean;legal?:boolean;children:React.ReactNode}){
  const nav=legal?[["/juridique","Dossiers juridiques"],["/juridique/originaux","Originaux"],["/finance/prets","Suivi des prêts"]] as const:control?[["/finance/controles","Contrôles Finance"],["/finance/prets","Suivi des prêts"]] as const:admin?[["/administration/equipe","Équipe et accès"],["/administration/affectations","Affectations Finance"],["/administration/courriels","E-mails"]] as const:finance?[["/finance","Dossiers financiers"],["/finance/institutions","Institutions"],["/finance/prets","Suivi des prêts"],["/finance/simulation","Simulation"],["/finance/incidents","Incidents et réclamations"]] as const:staff?[["/gestion/acquereurs","Acquéreurs"],["/gestion/parcelles","Parcelles"],["/gestion/changements","Regroupements et titulaires"],["/gestion/messages","Messages"],["/gestion/publications","Publications"]] as const:[["/mykipcity","Mon espace Kip-City"],["/mykipcity/services","Mes services"],["/mykipcity/documents","Mes documents"],["/mykipcity/contact","Contact"]] as const;
  return <div className="app-shell"><aside className="sidebar"><Brand/><p className="nav-label">{legal?"CABINET JURIDIQUE":control?"CONTRÔLES FINANCE":admin?"ADMINISTRATION":finance?"FINANCE":staff?"GESTION DES ACQUÉREURS":"MON ESPACE"}</p><ShellNavigation items={nav.map(([href,label])=>({href,label}))}/><div className="sidebar-bottom">{!staff&&!finance&&!admin&&!control&&!legal&&<div className="sidebar-help"><h3>Une question ?</h3><p>Votre équipe vous accompagne.</p><Link href="/mykipcity/contact">Nous écrire ↗</Link></div>}<a href="https://kip-city.com" target="_blank" rel="noreferrer">Site public <ArrowUpRight size={15}/></a></div></aside><div className="workspace"><header className="topbar"><MobileNavigation items={nav.map(([href,label])=>({href,label}))} title={legal?"Cabinet juridique":control?"Contrôles Finance":admin?"Administration":finance?"Finance":staff?"Gestion des acquéreurs":"Mon espace Kip-City"} name={name} member={!staff&&!finance&&!admin&&!control&&!legal} brand={<Brand/>} notifications={<NotificationLink/>}/><span className="workspace-label">{legal?"Cabinet juridique":control?"Contrôles Finance":admin?"Administration":finance?"Finance":staff?"Gestion des acquéreurs":"MyKipCity · Mon espace"}</span><div className="account"><NotificationLink/><span className="avatar">{name.slice(0,1)}</span><span>{name}</span>{!staff&&!finance&&!admin&&!control&&!legal&&<Link className="text-link" href="/mykipcity/profil">Mon profil</Link>}<Link href="/compte" className="text-link">Sécurité</Link><Logout/></div></header><main id="main-content">{children}</main><footer className="app-footer">Kip-City · MyKipCity <span>Espace privé</span></footer></div></div>;
}
export function Heading({eyebrow,title,description,children}:{eyebrow:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{children}</div>;}
const labels:Record<string,string>={ACCESS_REVOKED:"Accès retiré",ACCESS_EXPIRED:"Droits expirés",DRAFT:"À compléter",SUBMITTED:"En cours d’examen",NEEDS_INFO:"Complément demandé",VERIFIED:"Dossier vérifié",CLOSED:"Dossier clôturé",PENDING:"À vérifier",APPROVED:"Rattachement validé",REJECTED:"Rattachement refusé",MANUAL_REVIEW:"Examen manuel requis"};
export function Status({value}:{value:string}){return <span className={`status ${value==="APPROVED"||value==="VERIFIED"?"positive":""}`}>{labels[value]??value}</span>;}
