import Link from "next/link";
import {notFound} from "next/navigation";
import {pageActor} from "@/lib/session";
import {getOriginal} from "@/lib/originals";
import {db} from "@/lib/db";
import {WorkflowError} from "@/lib/workflow";
import {originalSituation,originalStates,originalKinds,eventStates,originalData,type OriginalData} from "@/lib/original-model";
import {inventoryLabels,movementLabels} from "@/lib/original-labels";
import {Shell,Heading} from "@/components/shell";
import {OriginalForm,OriginalDecision} from "@/components/original-forms";
function Details({data}:{data:OriginalData}){return <><dl><dt>Date du fait · Kinshasa</dt><dd>{data.occurredAt.replace("T"," à ")}</dd>{Object.entries(movementLabels).map(([key,label])=>data[key as keyof typeof movementLabels]?<div key={key}><dt>{label}</dt><dd style={{whiteSpace:"pre-wrap"}}>{data[key as keyof typeof movementLabels]}</dd></div>:null)}{data.returnDue&&<><dt>Retour attendu</dt><dd>{data.returnDue}</dd></>}{data.returnTerms&&<><dt>Événement attendu pour le retour</dt><dd>{data.returnTerms}</dd></>}</dl>{data.inventory&&<details><summary>Inventaire lors de la remise</summary><dl>{Object.entries(inventoryLabels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{data.inventory![key as keyof typeof inventoryLabels]}</dd></div>)}</dl><p>Copie et reçu déclarés remis. Authenticité et portée déclarées examinées séparément.</p></details>}</>;}
export default async function OriginalDetail({params}:{params:Promise<{id:string}>}){
 const actor=await pageActor(),{item}=await getOriginal(actor.id,(await params).id).catch(e=>{if(e instanceof WorkflowError&&e.status===404)notFound();throw e;}),s=originalSituation(item.events),last=s.effective.at(-1),pending=item.events.find(e=>e.status==="PENDING"),owner=actor.role==="LEGAL_OFFICER"&&item.case.legalOfficerId===actor.id;
 const reviewers=owner?await db.user.findMany({where:{active:true,role:"LEGAL_OFFICER",personId:{not:actor.personId}},select:{id:true,name:true},orderBy:{name:"asc"}}):[];
 const kinds:(keyof typeof originalKinds)[]=s.state==="UNCONFIRMED"?["DEPOSIT"]:s.state==="LOST"?["FOUND"]:s.state==="RETURNED"?[]:s.state==="OUT"?["RETURN_TO_CUSTODY","TRANSFER","FINAL_RETURN","LOSS","DAMAGE"]:["TEMPORARY_OUT","TRANSFER","FINAL_RETURN","LOSS","DAMAGE"];
 return <Shell name={actor.name} legal={actor.role==="LEGAL_OFFICER"} finance={actor.role==="FINANCE_OFFICER"} control={actor.role==="FINANCE_REVIEWER"||actor.role==="FINANCE_VALIDATOR"}><Link href="/juridique/originaux" className="text-link">← Registre des originaux</Link><Heading eyebrow={`${item.case.reference} · ${item.case.applicantName}`} title={item.reference}><span className="status">{originalStates[s.state]}</span></Heading><section className="panel"><h2>{s.inventory?.nature??"Inventaire en cours"}</h2>{s.last?<><p><strong>Détenteur confirmé :</strong> {s.last.holder}</p><p><strong>Lieu de conservation :</strong> {s.last.location}</p><p><strong>État :</strong> {s.last.condition}</p>{s.returnDue&&<p>Retour attendu le {s.returnDue}</p>}{s.returnTerms&&<p>Événement de retour : {s.returnTerms}</p>}</>:<p>La remise initiale attend son contrôle.</p>}{pending&&<p className="feedback">{originalKinds[originalData.parse(pending.data).kind]} déclaré : contrôle en attente. La situation confirmée ci-dessus n’est pas encore mise à jour.</p>}{s.state==="RETURNED"&&<p>Restitution constatée. Les inscriptions, garanties et recours restent examinés séparément.</p>}</section>
 {owner&&!pending&&<section className="panel">{kinds.length>0&&<details><summary>{s.state==="UNCONFIRMED"?"Reprendre la remise initiale":"Enregistrer un mouvement"}</summary><OriginalForm key={`new-${item.version}`} caseId={item.caseId} id={item.id} reference={item.reference} version={item.version} reviewers={reviewers} kinds={kinds} last={last?{id:last.id,data:last.data}:undefined} initial={s.state==="UNCONFIRMED"&&item.events[0]?originalData.parse(item.events[0].data):undefined}/></details>}{last&&<details><summary>Corriger le dernier fait contrôlé</summary><OriginalForm key={`correction-${item.version}`} caseId={item.caseId} id={item.id} reference={item.reference} version={item.version} reviewers={reviewers} kinds={[last.data.kind]} last={{id:last.id,data:last.data}} correction/></details>}</section>}
 <section className="panel"><h2>Historique et reçus</h2>{item.events.map(e=>{const data=originalData.parse(e.data),replaced=e.status==="ACCEPTED"&&!s.effective.some(f=>f.id===e.id);return <details key={e.id} id={`fait-${e.id}`} open={e.status==="PENDING"}><summary>{originalKinds[data.kind]} · {data.occurredAt.replace("T"," ")} · {replaced?"Corrigé":eventStates[e.status]}</summary><Details data={data}/>{e.replacesId&&<p><a href={`#fait-${e.replacesId}`} className="text-link">Voir le fait corrigé</a></p>}<a href={`/api/juridique/originaux/preuves/${e.id}`} className="text-link">Télécharger {e.originalName}</a><p className="small muted">Saisi par {e.authorName} le {e.createdAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}</p>{e.reviewedAt&&<p>{e.status==="CANCELLED"?"Retrait":"Contrôle"} : {e.reviewerName} · {e.reviewedAt.toLocaleString("fr-FR",{timeZone:"Africa/Kinshasa"})}<br/>{e.reviewReason}</p>}{e.status==="PENDING"&&e.reviewerId===actor.id&&actor.role==="LEGAL_OFFICER"&&<OriginalDecision id={e.id} version={item.version}/>} {e.status==="PENDING"&&owner&&<details><summary>Retirer cette saisie du contrôle</summary><OriginalDecision id={e.id} version={item.version} cancel/></details>}</details>;})}</section></Shell>;
}
